/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      icon: 'fluent:book-information-24-regular',
      order: 10,
      hideInMenu: true
    }
  },
  {
    name: 'alarm',
    path: '/alarm',
    component: 'layout.base',
    meta: {
      title: 'alarm',
      i18nKey: 'route.alarm',
      icon: 'mdi:alert-outline',
      order: 50
    },
    children: [
      {
        name: 'alarm_history',
        path: '/alarm/history',
        component: 'view.alarm_history',
        meta: {
          title: 'alarm_history',
          i18nKey: 'route.alarm_history',
          icon: 'mdi:history',
          order: 2
        }
      },
      {
        name: 'alarm_item',
        path: '/alarm/item',
        component: 'view.alarm_item',
        meta: {
          title: 'alarm_item',
          i18nKey: 'route.alarm_item',
          icon: 'mdi:bell-cog-outline',
          order: 1
        }
      },
      {
        name: 'alarm_limit-type',
        path: '/alarm/limit-type',
        component: 'view.alarm_limit-type',
        meta: {
          title: 'alarm_limit-type',
          i18nKey: 'route.alarm_limit-type',
          icon: 'mdi:format-list-bulleted-type',
          order: 3
        }
      }
    ]
  },
  {
    name: 'analysis',
    path: '/analysis',
    component: 'layout.base',
    meta: {
      title: 'analysis',
      i18nKey: 'route.analysis',
      icon: 'ant-design:bar-chart-outlined',
      order: 75
    },
    children: [
      {
        name: 'analysis_benchmark',
        path: '/analysis/benchmark',
        component: 'view.analysis_benchmark',
        meta: {
          title: 'analysis_benchmark',
          i18nKey: 'route.analysis_benchmark',
          icon: 'ant-design:aim-outlined',
          order: 1
        }
      },
      {
        name: 'analysis_branch',
        path: '/analysis/branch',
        component: 'view.analysis_branch',
        meta: {
          title: 'analysis_branch',
          i18nKey: 'route.analysis_branch',
          icon: 'ant-design:branches-outlined',
          order: 2
        }
      },
      {
        name: 'analysis_comprehensive',
        path: '/analysis/comprehensive',
        component: 'view.analysis_comprehensive',
        meta: {
          title: 'analysis_comprehensive',
          i18nKey: 'route.analysis_comprehensive',
          icon: 'ant-design:pie-chart-outlined',
          order: 3
        }
      },
      {
        name: 'analysis_consumption',
        path: '/analysis/consumption',
        component: 'view.analysis_consumption',
        meta: {
          title: 'analysis_consumption',
          i18nKey: 'route.analysis_consumption',
          icon: 'ant-design:line-chart-outlined',
          order: 4
        }
      },
      {
        name: 'analysis_consumption-detail',
        path: '/analysis/consumption-detail',
        component: 'view.analysis_consumption-detail',
        meta: {
          title: 'analysis_consumption-detail',
          i18nKey: 'route.analysis_consumption-detail',
          hideInMenu: true,
          icon: 'ant-design:file-search-outlined',
          order: 5
        }
      },
      {
        name: 'analysis_energy',
        path: '/analysis/energy',
        meta: {
          title: 'analysis_energy',
          i18nKey: 'route.analysis_energy',
          icon: 'ant-design:pie-chart-outlined',
          order: 15
        },
        children: [
          {
            name: 'analysis_energy_comprehensive',
            path: '/analysis/energy/comprehensive',
            meta: {
              title: 'analysis_energy_comprehensive',
              i18nKey: 'route.analysis_energy_comprehensive'
            },
            children: [
              {
                name: 'analysis_energy_comprehensive_daily',
                path: '/analysis/energy/comprehensive/daily',
                component: 'view.analysis_energy_comprehensive_daily',
                meta: {
                  title: 'analysis_energy_comprehensive_daily',
                  i18nKey: 'route.analysis_energy_comprehensive_daily',
                  hideInMenu: true
                }
              },
              {
                name: 'analysis_energy_comprehensive_monthly',
                path: '/analysis/energy/comprehensive/monthly',
                component: 'view.analysis_energy_comprehensive_monthly',
                meta: {
                  title: 'analysis_energy_comprehensive_monthly',
                  i18nKey: 'route.analysis_energy_comprehensive_monthly',
                  hideInMenu: true
                }
              },
              {
                name: 'analysis_energy_comprehensive_statistics',
                path: '/analysis/energy/comprehensive/statistics',
                component: 'view.analysis_energy_comprehensive_statistics',
                meta: {
                  title: 'analysis_energy_comprehensive_statistics',
                  i18nKey: 'route.analysis_energy_comprehensive_statistics',
                  hideInMenu: true
                }
              },
              {
                name: 'analysis_energy_comprehensive_year',
                path: '/analysis/energy/comprehensive/year',
                component: 'view.analysis_energy_comprehensive_year',
                meta: {
                  title: 'analysis_energy_comprehensive_year',
                  i18nKey: 'route.analysis_energy_comprehensive_year',
                  hideInMenu: true
                }
              }
            ]
          }
        ]
      },
      {
        name: 'analysis_indicators',
        path: '/analysis/indicators',
        component: 'view.analysis_indicators',
        meta: {
          title: 'analysis_indicators',
          i18nKey: 'route.analysis_indicators',
          icon: 'ant-design:dashboard-outlined',
          order: 6
        }
      },
      {
        name: 'analysis_itemized',
        path: '/analysis/itemized',
        component: 'view.analysis_itemized',
        meta: {
          title: 'analysis_itemized',
          i18nKey: 'route.analysis_itemized',
          icon: 'ant-design:appstore-outlined',
          order: 7
        }
      },
      {
        name: 'analysis_itemized-detail',
        path: '/analysis/itemized-detail',
        component: 'view.analysis_itemized-detail',
        meta: {
          title: 'analysis_itemized-detail',
          i18nKey: 'route.analysis_itemized-detail',
          hideInMenu: true,
          icon: 'ant-design:file-search-outlined',
          order: 8
        }
      },
      {
        name: 'analysis_key-equipment',
        path: '/analysis/key-equipment',
        meta: {
          title: 'analysis_key-equipment',
          i18nKey: 'route.analysis_key-equipment',
          icon: 'ant-design:dashboard-outlined',
          order: 13
        },
        children: [
          {
            name: 'analysis_key-equipment_daily',
            path: '/analysis/key-equipment/daily',
            component: 'view.analysis_key-equipment_daily',
            meta: {
              title: 'analysis_key-equipment_daily',
              i18nKey: 'route.analysis_key-equipment_daily',
              hideInMenu: true
            }
          },
          {
            name: 'analysis_key-equipment_monthly',
            path: '/analysis/key-equipment/monthly',
            component: 'view.analysis_key-equipment_monthly',
            meta: {
              title: 'analysis_key-equipment_monthly',
              i18nKey: 'route.analysis_key-equipment_monthly',
              hideInMenu: true
            }
          },
          {
            name: 'analysis_key-equipment_year',
            path: '/analysis/key-equipment/year',
            component: 'view.analysis_key-equipment_year',
            meta: {
              title: 'analysis_key-equipment_year',
              i18nKey: 'route.analysis_key-equipment_year',
              hideInMenu: true
            }
          }
        ]
      },
      {
        name: 'analysis_peak-valley',
        path: '/analysis/peak-valley',
        component: 'view.analysis_peak-valley',
        meta: {
          title: 'analysis_peak-valley',
          i18nKey: 'route.analysis_peak-valley',
          icon: 'ant-design:rise-outlined',
          order: 9
        }
      },
      {
        name: 'analysis_peak-valley-detail',
        path: '/analysis/peak-valley-detail',
        component: 'view.analysis_peak-valley-detail',
        meta: {
          title: 'analysis_peak-valley-detail',
          i18nKey: 'route.analysis_peak-valley-detail',
          hideInMenu: true,
          icon: 'ant-design:file-search-outlined',
          order: 10
        }
      },
      {
        name: 'analysis_peak-valley-scheme',
        path: '/analysis/peak-valley-scheme',
        component: 'view.analysis_peak-valley-scheme',
        meta: {
          title: 'analysis_peak-valley-scheme',
          i18nKey: 'route.analysis_peak-valley-scheme',
          icon: 'ant-design:setting-outlined',
          order: 11
        }
      },
      {
        name: 'analysis_process-energy',
        path: '/analysis/process-energy',
        meta: {
          title: 'analysis_process-energy',
          i18nKey: 'route.analysis_process-energy',
          icon: 'ant-design:cluster-outlined',
          order: 14
        },
        children: [
          {
            name: 'analysis_process-energy_statistics',
            path: '/analysis/process-energy/statistics',
            meta: {
              title: 'analysis_process-energy_statistics',
              i18nKey: 'route.analysis_process-energy_statistics'
            },
            children: [
              {
                name: 'analysis_process-energy_statistics_daily',
                path: '/analysis/process-energy/statistics/daily',
                component: 'view.analysis_process-energy_statistics_daily',
                meta: {
                  title: 'analysis_process-energy_statistics_daily',
                  i18nKey: 'route.analysis_process-energy_statistics_daily',
                  hideInMenu: true
                }
              },
              {
                name: 'analysis_process-energy_statistics_monthly',
                path: '/analysis/process-energy/statistics/monthly',
                component: 'view.analysis_process-energy_statistics_monthly',
                meta: {
                  title: 'analysis_process-energy_statistics_monthly',
                  i18nKey: 'route.analysis_process-energy_statistics_monthly',
                  hideInMenu: true
                }
              },
              {
                name: 'analysis_process-energy_statistics_year',
                path: '/analysis/process-energy/statistics/year',
                component: 'view.analysis_process-energy_statistics_year',
                meta: {
                  title: 'analysis_process-energy_statistics_year',
                  i18nKey: 'route.analysis_process-energy_statistics_year',
                  hideInMenu: true
                }
              }
            ]
          }
        ]
      },
      {
        name: 'analysis_product-output',
        path: '/analysis/product-output',
        component: 'view.analysis_product-output',
        meta: {
          title: 'analysis_product-output',
          i18nKey: 'route.analysis_product-output',
          icon: 'ant-design:boxplot-outlined',
          order: 12
        }
      },
      {
        name: 'analysis_statistical',
        path: '/analysis/statistical',
        meta: {
          title: 'analysis_statistical',
          i18nKey: 'route.analysis_statistical',
          icon: 'ant-design:bar-chart-outlined',
          order: 16
        },
        children: [
          {
            name: 'analysis_statistical_cost',
            path: '/analysis/statistical/cost',
            component: 'view.analysis_statistical_cost',
            meta: {
              title: 'analysis_statistical_cost',
              i18nKey: 'route.analysis_statistical_cost',
              hideInMenu: true,
              icon: 'ant-design:dollar-outlined',
              order: 17
            }
          },
          {
            name: 'analysis_statistical_flow',
            path: '/analysis/statistical/flow',
            component: 'view.analysis_statistical_flow',
            meta: {
              title: 'analysis_statistical_flow',
              i18nKey: 'route.analysis_statistical_flow',
              hideInMenu: true,
              icon: 'ant-design:branches-outlined',
              order: 18
            }
          },
          {
            name: 'analysis_statistical_yoy-mom',
            path: '/analysis/statistical/yoy-mom',
            component: 'view.analysis_statistical_yoy-mom',
            meta: {
              title: 'analysis_statistical_yoy-mom',
              i18nKey: 'route.analysis_statistical_yoy-mom',
              hideInMenu: true,
              icon: 'ant-design:stock-outlined',
              order: 19
            }
          }
        ]
      }
    ]
  },
  {
    name: 'approval',
    path: '/approval',
    component: 'layout.base',
    meta: {
      title: 'approval',
      i18nKey: 'route.approval',
      icon: 'ant-design:audit-outlined',
      order: 80
    },
    children: [
      {
        name: 'approval_flow-designer',
        path: '/approval/flow-designer',
        component: 'view.approval_flow-designer',
        meta: {
          title: 'approval_flow-designer',
          i18nKey: 'route.approval_flow-designer',
          icon: 'ant-design:branches-outlined',
          order: 1
        }
      },
      {
        name: 'approval_workspace',
        path: '/approval/workspace',
        component: 'view.approval_workspace',
        meta: {
          title: 'approval_workspace',
          i18nKey: 'route.approval_workspace',
          icon: 'ant-design:desktop-outlined',
          order: 2
        }
      }
    ]
  },
  {
    name: 'base-data',
    path: '/base-data',
    component: 'layout.base',
    meta: {
      title: 'base-data',
      i18nKey: 'route.base-data',
      icon: 'ant-design:database-outlined',
      order: 40
    },
    children: [
      {
        name: 'base-data_coefficient',
        path: '/base-data/coefficient',
        component: 'view.base-data_coefficient',
        meta: {
          title: 'base-data_coefficient',
          i18nKey: 'route.base-data_coefficient',
          icon: 'ant-design:calculator-outlined',
          order: 3
        }
      },
      {
        name: 'base-data_home',
        path: '/base-data/home',
        component: 'view.base-data_home',
        meta: {
          title: 'base-data_home',
          i18nKey: 'route.base-data_home',
          icon: 'ant-design:home-outlined',
          order: 0
        }
      },
      {
        name: 'base-data_medium',
        path: '/base-data/medium',
        component: 'view.base-data_medium',
        meta: {
          title: 'base-data_medium',
          i18nKey: 'route.base-data_medium',
          icon: 'ant-design:appstore-outlined',
          order: 1
        }
      },
      {
        name: 'base-data_meter',
        path: '/base-data/meter',
        component: 'view.base-data_meter',
        meta: {
          title: 'base-data_meter',
          i18nKey: 'route.base-data_meter',
          icon: 'ant-design:dashboard-outlined',
          order: 4
        }
      },
      {
        name: 'base-data_power-distribution',
        path: '/base-data/power-distribution',
        component: 'view.base-data_power-distribution',
        meta: {
          title: 'base-data_power-distribution',
          i18nKey: 'route.base-data_power-distribution',
          icon: 'ant-design:electrical-service-outlined',
          order: 7
        }
      },
      {
        name: 'base-data_tou',
        path: '/base-data/tou',
        component: 'view.base-data_tou',
        meta: {
          title: 'base-data_tou',
          i18nKey: 'route.base-data_tou',
          icon: 'ant-design:clock-circle-outlined',
          order: 5
        }
      },
      {
        name: 'base-data_unit',
        path: '/base-data/unit',
        component: 'view.base-data_unit',
        meta: {
          title: 'base-data_unit',
          i18nKey: 'route.base-data_unit',
          icon: 'ant-design:swap-outlined',
          order: 2
        }
      },
      {
        name: 'base-data_virtual-meter',
        path: '/base-data/virtual-meter',
        component: 'view.base-data_virtual-meter',
        meta: {
          title: 'base-data_virtual-meter',
          i18nKey: 'route.base-data_virtual-meter',
          icon: 'ant-design:build-outlined',
          order: 6
        }
      }
    ]
  },
  {
    name: 'cost',
    path: '/cost',
    component: 'layout.base',
    meta: {
      title: 'cost',
      i18nKey: 'route.cost',
      icon: 'ant-design:dollar-outlined',
      order: 60
    },
    children: [
      {
        name: 'cost_electricity',
        path: '/cost/electricity',
        component: 'view.cost_electricity',
        meta: {
          title: 'cost_electricity',
          i18nKey: 'route.cost_electricity',
          icon: 'ant-design:flash-outlined',
          order: 1
        }
      },
      {
        name: 'cost_tactics',
        path: '/cost/tactics',
        component: 'view.cost_tactics',
        meta: {
          title: 'cost_tactics',
          i18nKey: 'route.cost_tactics',
          icon: 'ant-design:bulb-outlined',
          order: 2
        }
      },
      {
        name: 'cost_trend',
        path: '/cost/trend',
        component: 'view.cost_trend',
        meta: {
          title: 'cost_trend',
          i18nKey: 'route.cost_trend',
          icon: 'ant-design:line-chart-outlined',
          order: 3
        }
      }
    ]
  },
  {
    name: 'dashboard',
    path: '/dashboard',
    component: 'layout.base',
    meta: {
      title: 'dashboard',
      i18nKey: 'route.dashboard',
      icon: 'ant-design:dashboard-outlined',
      order: 15
    },
    children: [
      {
        name: 'dashboard_custom',
        path: '/dashboard/custom',
        component: 'view.dashboard_custom',
        meta: {
          title: 'dashboard_custom',
          i18nKey: 'route.dashboard_custom',
          icon: 'ic:baseline-dashboard-customize',
          order: 1
        }
      }
    ]
  },
  {
    name: 'developer',
    path: '/developer',
    component: 'layout.base',
    meta: {
      title: 'developer',
      i18nKey: 'route.developer',
      hideInMenu: true
    },
    children: [
      {
        name: 'developer_function',
        path: '/developer/function',
        meta: {
          title: 'developer_function',
          i18nKey: 'route.developer_function',
          hideInMenu: true
        },
        children: [
          {
            name: 'developer_function_hide-child',
            path: '/developer/function/hide-child',
            meta: {
              title: 'developer_function_hide-child',
              i18nKey: 'route.developer_function_hide-child'
            },
            children: [
              {
                name: 'developer_function_hide-child_one',
                path: '/developer/function/hide-child/one',
                component: 'view.developer_function_hide-child_one',
                meta: {
                  title: 'developer_function_hide-child_one',
                  i18nKey: 'route.developer_function_hide-child_one'
                }
              },
              {
                name: 'developer_function_hide-child_three',
                path: '/developer/function/hide-child/three',
                component: 'view.developer_function_hide-child_three',
                meta: {
                  title: 'developer_function_hide-child_three',
                  i18nKey: 'route.developer_function_hide-child_three'
                }
              },
              {
                name: 'developer_function_hide-child_two',
                path: '/developer/function/hide-child/two',
                component: 'view.developer_function_hide-child_two',
                meta: {
                  title: 'developer_function_hide-child_two',
                  i18nKey: 'route.developer_function_hide-child_two'
                }
              }
            ]
          },
          {
            name: 'developer_function_multi-tab',
            path: '/developer/function/multi-tab',
            component: 'view.developer_function_multi-tab',
            meta: {
              title: 'developer_function_multi-tab',
              i18nKey: 'route.developer_function_multi-tab'
            }
          },
          {
            name: 'developer_function_request',
            path: '/developer/function/request',
            component: 'view.developer_function_request',
            meta: {
              title: 'developer_function_request',
              i18nKey: 'route.developer_function_request'
            }
          },
          {
            name: 'developer_function_super-page',
            path: '/developer/function/super-page',
            component: 'view.developer_function_super-page',
            meta: {
              title: 'developer_function_super-page',
              i18nKey: 'route.developer_function_super-page'
            }
          },
          {
            name: 'developer_function_tab',
            path: '/developer/function/tab',
            component: 'view.developer_function_tab',
            meta: {
              title: 'developer_function_tab',
              i18nKey: 'route.developer_function_tab'
            }
          },
          {
            name: 'developer_function_toggle-auth',
            path: '/developer/function/toggle-auth',
            component: 'view.developer_function_toggle-auth',
            meta: {
              title: 'developer_function_toggle-auth',
              i18nKey: 'route.developer_function_toggle-auth'
            }
          }
        ]
      },
      {
        name: 'developer_plugin',
        path: '/developer/plugin',
        meta: {
          title: 'developer_plugin',
          i18nKey: 'route.developer_plugin',
          hideInMenu: true
        },
        children: [
          {
            name: 'developer_plugin_barcode',
            path: '/developer/plugin/barcode',
            component: 'view.developer_plugin_barcode',
            meta: {
              title: 'developer_plugin_barcode',
              i18nKey: 'route.developer_plugin_barcode'
            }
          },
          {
            name: 'developer_plugin_charts',
            path: '/developer/plugin/charts',
            meta: {
              title: 'developer_plugin_charts',
              i18nKey: 'route.developer_plugin_charts'
            },
            children: [
              {
                name: 'developer_plugin_charts_antv',
                path: '/developer/plugin/charts/antv',
                component: 'view.developer_plugin_charts_antv',
                meta: {
                  title: 'developer_plugin_charts_antv',
                  i18nKey: 'route.developer_plugin_charts_antv'
                }
              },
              {
                name: 'developer_plugin_charts_echarts',
                path: '/developer/plugin/charts/echarts',
                component: 'view.developer_plugin_charts_echarts',
                meta: {
                  title: 'developer_plugin_charts_echarts',
                  i18nKey: 'route.developer_plugin_charts_echarts'
                }
              },
              {
                name: 'developer_plugin_charts_vchart',
                path: '/developer/plugin/charts/vchart',
                component: 'view.developer_plugin_charts_vchart',
                meta: {
                  title: 'developer_plugin_charts_vchart',
                  i18nKey: 'route.developer_plugin_charts_vchart'
                }
              }
            ]
          },
          {
            name: 'developer_plugin_copy',
            path: '/developer/plugin/copy',
            component: 'view.developer_plugin_copy',
            meta: {
              title: 'developer_plugin_copy',
              i18nKey: 'route.developer_plugin_copy'
            }
          },
          {
            name: 'developer_plugin_editor',
            path: '/developer/plugin/editor',
            meta: {
              title: 'developer_plugin_editor',
              i18nKey: 'route.developer_plugin_editor'
            },
            children: [
              {
                name: 'developer_plugin_editor_markdown',
                path: '/developer/plugin/editor/markdown',
                component: 'view.developer_plugin_editor_markdown',
                meta: {
                  title: 'developer_plugin_editor_markdown',
                  i18nKey: 'route.developer_plugin_editor_markdown'
                }
              },
              {
                name: 'developer_plugin_editor_quill',
                path: '/developer/plugin/editor/quill',
                component: 'view.developer_plugin_editor_quill',
                meta: {
                  title: 'developer_plugin_editor_quill',
                  i18nKey: 'route.developer_plugin_editor_quill'
                }
              }
            ]
          },
          {
            name: 'developer_plugin_excel',
            path: '/developer/plugin/excel',
            component: 'view.developer_plugin_excel',
            meta: {
              title: 'developer_plugin_excel',
              i18nKey: 'route.developer_plugin_excel'
            }
          },
          {
            name: 'developer_plugin_gantt',
            path: '/developer/plugin/gantt',
            meta: {
              title: 'developer_plugin_gantt',
              i18nKey: 'route.developer_plugin_gantt'
            },
            children: [
              {
                name: 'developer_plugin_gantt_dhtmlx',
                path: '/developer/plugin/gantt/dhtmlx',
                component: 'view.developer_plugin_gantt_dhtmlx',
                meta: {
                  title: 'developer_plugin_gantt_dhtmlx',
                  i18nKey: 'route.developer_plugin_gantt_dhtmlx'
                }
              },
              {
                name: 'developer_plugin_gantt_vtable',
                path: '/developer/plugin/gantt/vtable',
                component: 'view.developer_plugin_gantt_vtable',
                meta: {
                  title: 'developer_plugin_gantt_vtable',
                  i18nKey: 'route.developer_plugin_gantt_vtable'
                }
              }
            ]
          },
          {
            name: 'developer_plugin_icon',
            path: '/developer/plugin/icon',
            component: 'view.developer_plugin_icon',
            meta: {
              title: 'developer_plugin_icon',
              i18nKey: 'route.developer_plugin_icon'
            }
          },
          {
            name: 'developer_plugin_map',
            path: '/developer/plugin/map',
            component: 'view.developer_plugin_map',
            meta: {
              title: 'developer_plugin_map',
              i18nKey: 'route.developer_plugin_map'
            }
          },
          {
            name: 'developer_plugin_pdf',
            path: '/developer/plugin/pdf',
            component: 'view.developer_plugin_pdf',
            meta: {
              title: 'developer_plugin_pdf',
              i18nKey: 'route.developer_plugin_pdf'
            }
          },
          {
            name: 'developer_plugin_pinyin',
            path: '/developer/plugin/pinyin',
            component: 'view.developer_plugin_pinyin',
            meta: {
              title: 'developer_plugin_pinyin',
              i18nKey: 'route.developer_plugin_pinyin'
            }
          },
          {
            name: 'developer_plugin_print',
            path: '/developer/plugin/print',
            component: 'view.developer_plugin_print',
            meta: {
              title: 'developer_plugin_print',
              i18nKey: 'route.developer_plugin_print'
            }
          },
          {
            name: 'developer_plugin_swiper',
            path: '/developer/plugin/swiper',
            component: 'view.developer_plugin_swiper',
            meta: {
              title: 'developer_plugin_swiper',
              i18nKey: 'route.developer_plugin_swiper'
            }
          },
          {
            name: 'developer_plugin_tables',
            path: '/developer/plugin/tables',
            meta: {
              title: 'developer_plugin_tables',
              i18nKey: 'route.developer_plugin_tables'
            },
            children: [
              {
                name: 'developer_plugin_tables_vtable',
                path: '/developer/plugin/tables/vtable',
                component: 'view.developer_plugin_tables_vtable',
                meta: {
                  title: 'developer_plugin_tables_vtable',
                  i18nKey: 'route.developer_plugin_tables_vtable'
                }
              }
            ]
          },
          {
            name: 'developer_plugin_typeit',
            path: '/developer/plugin/typeit',
            component: 'view.developer_plugin_typeit',
            meta: {
              title: 'developer_plugin_typeit',
              i18nKey: 'route.developer_plugin_typeit'
            }
          },
          {
            name: 'developer_plugin_video',
            path: '/developer/plugin/video',
            component: 'view.developer_plugin_video',
            meta: {
              title: 'developer_plugin_video',
              i18nKey: 'route.developer_plugin_video'
            }
          }
        ]
      }
    ]
  },
  {
    name: 'energy',
    path: '/energy',
    component: 'layout.base',
    meta: {
      title: 'energy',
      i18nKey: 'route.energy',
      icon: 'ant-design:thunderbolt-outlined',
      order: 20
    },
    children: [
      {
        name: 'energy_branch-analysis',
        path: '/energy/branch-analysis',
        component: 'view.energy_branch-analysis',
        meta: {
          title: 'energy_branch-analysis',
          i18nKey: 'route.energy_branch-analysis',
          icon: 'ant-design:branches-outlined',
          order: 8
        }
      },
      {
        name: 'energy_comparison',
        path: '/energy/comparison',
        component: 'view.energy_comparison',
        meta: {
          title: 'energy_comparison',
          i18nKey: 'route.energy_comparison',
          icon: 'carbon:compare',
          order: 3
        }
      },
      {
        name: 'energy_dashboard',
        path: '/energy/dashboard',
        component: 'view.energy_dashboard',
        meta: {
          title: 'energy_dashboard',
          i18nKey: 'route.energy_dashboard',
          icon: 'mdi:monitor-dashboard',
          order: 1
        }
      },
      {
        name: 'energy_electric-analysis',
        path: '/energy/electric-analysis',
        component: 'view.energy_electric-analysis',
        meta: {
          title: 'energy_electric-analysis',
          i18nKey: 'route.energy_electric-analysis',
          icon: 'ant-design:flash-outlined',
          order: 6
        }
      },
      {
        name: 'energy_flow',
        path: '/energy/flow',
        component: 'view.energy_flow',
        meta: {
          title: 'energy_flow',
          i18nKey: 'route.energy_flow',
          icon: 'mdi:chart-sankey',
          order: 2
        }
      },
      {
        name: 'energy_history-data',
        path: '/energy/history-data',
        component: 'view.energy_history-data',
        meta: {
          title: 'energy_history-data',
          i18nKey: 'route.energy_history-data',
          icon: 'mdi:history',
          order: 7
        }
      },
      {
        name: 'energy_ranking',
        path: '/energy/ranking',
        component: 'view.energy_ranking',
        meta: {
          title: 'energy_ranking',
          i18nKey: 'route.energy_ranking',
          icon: 'carbon:chart-radar',
          order: 4
        }
      },
      {
        name: 'energy_report',
        path: '/energy/report',
        component: 'view.energy_report',
        meta: {
          title: 'energy_report',
          i18nKey: 'route.energy_report',
          icon: 'ant-design:file-text-outlined',
          order: 5
        }
      }
    ]
  },
  {
    name: 'gatewaysetting',
    path: '/gatewaysetting',
    component: 'layout.base$view.gatewaysetting',
    meta: {
      title: 'gatewaysetting',
      i18nKey: 'route.gatewaysetting',
      icon: 'mdi:router-wireless',
      order: 110
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'knowledge',
    path: '/knowledge',
    component: 'layout.base$view.knowledge',
    meta: {
      title: 'knowledge',
      i18nKey: 'route.knowledge',
      icon: 'mdi:book-open-page-variant',
      order: 100
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      icon: 'carbon:cloud-service-management',
      order: 9,
      roles: ['R_ADMIN']
    },
    children: [
      {
        name: 'manage_announcement',
        path: '/manage/announcement',
        component: 'view.manage_announcement',
        meta: {
          title: 'manage_announcement',
          i18nKey: 'route.manage_announcement',
          icon: 'ant-design:notification-outlined',
          order: 12
        }
      },
      {
        name: 'manage_api',
        path: '/manage/api',
        component: 'view.manage_api',
        meta: {
          title: 'manage_api',
          i18nKey: 'route.manage_api',
          icon: 'ant-design:api-outlined',
          order: 4
        }
      },
      {
        name: 'manage_approval-definition',
        path: '/manage/approval-definition',
        component: 'view.manage_approval-definition',
        meta: {
          title: 'manage_approval-definition',
          i18nKey: 'route.manage_approval-definition',
          icon: 'ant-design:audit-outlined',
          order: 10
        }
      },
      {
        name: 'manage_audit-log',
        path: '/manage/audit-log',
        component: 'view.manage_audit-log',
        meta: {
          title: 'manage_audit-log',
          i18nKey: 'route.manage_audit-log',
          icon: 'ant-design:file-text-outlined',
          order: 5
        }
      },
      {
        name: 'manage_dictionary',
        path: '/manage/dictionary',
        component: 'view.manage_dictionary',
        meta: {
          title: 'manage_dictionary',
          i18nKey: 'route.manage_dictionary',
          icon: 'ant-design:book-outlined',
          order: 6
        }
      },
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu',
          icon: 'material-symbols:route',
          order: 3,
          roles: ['R_ADMIN'],
          keepAlive: true
        }
      },
      {
        name: 'manage_notification-center',
        path: '/manage/notification-center',
        component: 'view.manage_notification-center',
        meta: {
          title: 'manage_notification-center',
          i18nKey: 'route.manage_notification-center',
          icon: 'ant-design:notification-outlined',
          order: 11
        }
      },
      {
        name: 'manage_organization',
        path: '/manage/organization',
        component: 'view.manage_organization',
        meta: {
          title: 'manage_organization',
          i18nKey: 'route.manage_organization',
          icon: 'ant-design:apartment-outlined',
          order: 7
        }
      },
      {
        name: 'manage_password-change',
        path: '/manage/password-change',
        component: 'view.manage_password-change',
        meta: {
          title: 'manage_password-change',
          i18nKey: 'route.manage_password-change',
          icon: 'ant-design:lock-outlined',
          order: 8
        }
      },
      {
        name: 'manage_policy',
        path: '/manage/policy',
        component: 'view.manage_policy',
        meta: {
          title: 'manage_policy',
          i18nKey: 'route.manage_policy',
          icon: 'ant-design:safety-outlined',
          order: 13
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role',
          icon: 'carbon:user-role',
          order: 2,
          roles: ['R_SUPER']
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user',
          icon: 'ic:round-manage-accounts',
          order: 1,
          roles: ['R_ADMIN']
        }
      },
      {
        name: 'manage_user-detail',
        path: '/manage/user-detail/:id',
        component: 'view.manage_user-detail',
        props: true,
        meta: {
          title: 'manage_user-detail',
          i18nKey: 'route.manage_user-detail',
          hideInMenu: true,
          roles: ['R_ADMIN'],
          activeMenu: 'manage_user'
        }
      },
      {
        name: 'manage_user-lock',
        path: '/manage/user-lock',
        component: 'view.manage_user-lock',
        meta: {
          title: 'manage_user-lock',
          i18nKey: 'route.manage_user-lock',
          icon: 'ant-design:user-delete-outlined',
          order: 9
        }
      }
    ]
  },
  {
    name: 'profile',
    path: '/profile',
    component: 'layout.base',
    meta: {
      title: 'profile',
      i18nKey: 'route.profile',
      icon: 'ant-design:user-outlined',
      order: 120
    },
    children: [
      {
        name: 'profile_info',
        path: '/profile/info',
        component: 'view.profile_info',
        meta: {
          title: 'profile_info',
          i18nKey: 'route.profile_info',
          icon: 'ant-design:user-outlined',
          order: 1
        }
      },
      {
        name: 'profile_password',
        path: '/profile/password',
        component: 'view.profile_password',
        meta: {
          title: 'profile_password',
          i18nKey: 'route.profile_password',
          icon: 'ant-design:lock-outlined',
          order: 2
        }
      }
    ]
  },
  {
    name: 'scheduling',
    path: '/scheduling',
    component: 'layout.base',
    meta: {
      title: 'scheduling',
      i18nKey: 'route.scheduling',
      icon: 'ant-design:schedule-outlined',
      order: 30
    },
    children: [
      {
        name: 'scheduling_calendar',
        path: '/scheduling/calendar',
        component: 'view.scheduling_calendar',
        meta: {
          title: 'scheduling_calendar',
          i18nKey: 'route.scheduling_calendar',
          icon: 'ant-design:calendar-outlined',
          order: 4
        }
      },
      {
        name: 'scheduling_factory-calendar',
        path: '/scheduling/factory-calendar',
        component: 'view.scheduling_factory-calendar',
        meta: {
          title: 'scheduling_factory-calendar',
          i18nKey: 'route.scheduling_factory-calendar',
          icon: 'ant-design:calendar-outlined',
          order: 5
        }
      },
      {
        name: 'scheduling_rule-config',
        path: '/scheduling/rule-config',
        component: 'view.scheduling_rule-config',
        meta: {
          title: 'scheduling_rule-config',
          i18nKey: 'route.scheduling_rule-config',
          icon: 'ant-design:setting-outlined',
          order: 6
        }
      },
      {
        name: 'scheduling_rule-template',
        path: '/scheduling/rule-template',
        component: 'view.scheduling_rule-template',
        meta: {
          title: 'scheduling_rule-template',
          i18nKey: 'route.scheduling_rule-template',
          icon: 'ant-design:copy-outlined',
          order: 8
        }
      },
      {
        name: 'scheduling_rule-version',
        path: '/scheduling/rule-version',
        component: 'view.scheduling_rule-version',
        meta: {
          title: 'scheduling_rule-version',
          i18nKey: 'route.scheduling_rule-version',
          icon: 'ant-design:history-outlined',
          order: 7
        }
      },
      {
        name: 'scheduling_shift',
        path: '/scheduling/shift',
        component: 'view.scheduling_shift',
        meta: {
          title: 'scheduling_shift',
          i18nKey: 'route.scheduling_shift',
          icon: 'ant-design:clock-circle-outlined',
          order: 2
        }
      },
      {
        name: 'scheduling_shift-pattern',
        path: '/scheduling/shift-pattern',
        component: 'view.scheduling_shift-pattern',
        meta: {
          title: 'scheduling_shift-pattern',
          i18nKey: 'route.scheduling_shift-pattern',
          icon: 'ant-design:sync-outlined',
          order: 3
        }
      },
      {
        name: 'scheduling_team',
        path: '/scheduling/team',
        component: 'view.scheduling_team',
        meta: {
          title: 'scheduling_team',
          i18nKey: 'route.scheduling_team',
          icon: 'ant-design:team-outlined',
          order: 1
        }
      }
    ]
  },
  {
    name: 'sustainability',
    path: '/sustainability',
    component: 'layout.base',
    meta: {
      title: 'sustainability',
      i18nKey: 'route.sustainability',
      icon: 'mdi:leaf',
      order: 70
    },
    children: [
      {
        name: 'sustainability_carbon-calculate',
        path: '/sustainability/carbon-calculate',
        component: 'view.sustainability_carbon-calculate',
        meta: {
          title: 'sustainability_carbon-calculate',
          i18nKey: 'route.sustainability_carbon-calculate',
          icon: 'mdi:molecule-co2',
          order: 3
        }
      },
      {
        name: 'sustainability_policy',
        path: '/sustainability/policy',
        component: 'view.sustainability_policy',
        meta: {
          title: 'sustainability_policy',
          i18nKey: 'route.sustainability_policy',
          icon: 'mdi:file-document-outline',
          order: 2
        }
      },
      {
        name: 'sustainability_program',
        path: '/sustainability/program',
        component: 'view.sustainability_program',
        meta: {
          title: 'sustainability_program',
          i18nKey: 'route.sustainability_program',
          icon: 'mdi:lightbulb-outline',
          order: 1
        }
      }
    ]
  }
];
