/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      icon: 'fluent:book-information-24-regular',
      order: 10
    }
  },
  {
    name: 'alarm',
    path: '/alarm',
    component: 'layout.base',
    meta: {
      title: 'alarm',
      i18nKey: 'route.alarm'
    },
    children: [
      {
        name: 'alarm_history',
        path: '/alarm/history',
        component: 'view.alarm_history',
        meta: {
          title: 'alarm_history',
          i18nKey: 'route.alarm_history'
        }
      },
      {
        name: 'alarm_item',
        path: '/alarm/item',
        component: 'view.alarm_item',
        meta: {
          title: 'alarm_item',
          i18nKey: 'route.alarm_item'
        }
      },
      {
        name: 'alarm_limit-type',
        path: '/alarm/limit-type',
        component: 'view.alarm_limit-type',
        meta: {
          title: 'alarm_limit-type',
          i18nKey: 'route.alarm_limit-type'
        }
      }
    ]
  },
  {
    name: 'analysis',
    path: '/analysis',
    component: 'layout.base',
    meta: {
      title: 'analysis',
      i18nKey: 'route.analysis'
    },
    children: [
      {
        name: 'analysis_benchmark',
        path: '/analysis/benchmark',
        component: 'view.analysis_benchmark',
        meta: {
          title: 'analysis_benchmark',
          i18nKey: 'route.analysis_benchmark'
        }
      },
      {
        name: 'analysis_branch',
        path: '/analysis/branch',
        component: 'view.analysis_branch',
        meta: {
          title: 'analysis_branch',
          i18nKey: 'route.analysis_branch'
        }
      },
      {
        name: 'analysis_comprehensive',
        path: '/analysis/comprehensive',
        component: 'view.analysis_comprehensive',
        meta: {
          title: 'analysis_comprehensive',
          i18nKey: 'route.analysis_comprehensive'
        }
      },
      {
        name: 'analysis_consumption',
        path: '/analysis/consumption',
        component: 'view.analysis_consumption',
        meta: {
          title: 'analysis_consumption',
          i18nKey: 'route.analysis_consumption'
        }
      },
      {
        name: 'analysis_consumption-detail',
        path: '/analysis/consumption-detail',
        component: 'view.analysis_consumption-detail',
        meta: {
          title: 'analysis_consumption-detail',
          i18nKey: 'route.analysis_consumption-detail'
        }
      },
      {
        name: 'analysis_energy',
        path: '/analysis/energy',
        meta: {
          title: 'analysis_energy',
          i18nKey: 'route.analysis_energy'
        },
        children: [
          {
            name: 'analysis_energy_comprehensive',
            path: '/analysis/energy/comprehensive',
            meta: {
              title: 'analysis_energy_comprehensive',
              i18nKey: 'route.analysis_energy_comprehensive'
            },
            children: [
              {
                name: 'analysis_energy_comprehensive_daily',
                path: '/analysis/energy/comprehensive/daily',
                component: 'view.analysis_energy_comprehensive_daily',
                meta: {
                  title: 'analysis_energy_comprehensive_daily',
                  i18nKey: 'route.analysis_energy_comprehensive_daily'
                }
              },
              {
                name: 'analysis_energy_comprehensive_monthly',
                path: '/analysis/energy/comprehensive/monthly',
                component: 'view.analysis_energy_comprehensive_monthly',
                meta: {
                  title: 'analysis_energy_comprehensive_monthly',
                  i18nKey: 'route.analysis_energy_comprehensive_monthly'
                }
              },
              {
                name: 'analysis_energy_comprehensive_statistics',
                path: '/analysis/energy/comprehensive/statistics',
                component: 'view.analysis_energy_comprehensive_statistics',
                meta: {
                  title: 'analysis_energy_comprehensive_statistics',
                  i18nKey: 'route.analysis_energy_comprehensive_statistics'
                }
              },
              {
                name: 'analysis_energy_comprehensive_year',
                path: '/analysis/energy/comprehensive/year',
                component: 'view.analysis_energy_comprehensive_year',
                meta: {
                  title: 'analysis_energy_comprehensive_year',
                  i18nKey: 'route.analysis_energy_comprehensive_year'
                }
              }
            ]
          }
        ]
      },
      {
        name: 'analysis_indicators',
        path: '/analysis/indicators',
        component: 'view.analysis_indicators',
        meta: {
          title: 'analysis_indicators',
          i18nKey: 'route.analysis_indicators'
        }
      },
      {
        name: 'analysis_itemized',
        path: '/analysis/itemized',
        component: 'view.analysis_itemized',
        meta: {
          title: 'analysis_itemized',
          i18nKey: 'route.analysis_itemized'
        }
      },
      {
        name: 'analysis_itemized-detail',
        path: '/analysis/itemized-detail',
        component: 'view.analysis_itemized-detail',
        meta: {
          title: 'analysis_itemized-detail',
          i18nKey: 'route.analysis_itemized-detail'
        }
      },
      {
        name: 'analysis_key-equipment',
        path: '/analysis/key-equipment',
        meta: {
          title: 'analysis_key-equipment',
          i18nKey: 'route.analysis_key-equipment'
        },
        children: [
          {
            name: 'analysis_key-equipment_daily',
            path: '/analysis/key-equipment/daily',
            component: 'view.analysis_key-equipment_daily',
            meta: {
              title: 'analysis_key-equipment_daily',
              i18nKey: 'route.analysis_key-equipment_daily'
            }
          },
          {
            name: 'analysis_key-equipment_monthly',
            path: '/analysis/key-equipment/monthly',
            component: 'view.analysis_key-equipment_monthly',
            meta: {
              title: 'analysis_key-equipment_monthly',
              i18nKey: 'route.analysis_key-equipment_monthly'
            }
          },
          {
            name: 'analysis_key-equipment_year',
            path: '/analysis/key-equipment/year',
            component: 'view.analysis_key-equipment_year',
            meta: {
              title: 'analysis_key-equipment_year',
              i18nKey: 'route.analysis_key-equipment_year'
            }
          }
        ]
      },
      {
        name: 'analysis_peak-valley',
        path: '/analysis/peak-valley',
        component: 'view.analysis_peak-valley',
        meta: {
          title: 'analysis_peak-valley',
          i18nKey: 'route.analysis_peak-valley'
        }
      },
      {
        name: 'analysis_peak-valley-detail',
        path: '/analysis/peak-valley-detail',
        component: 'view.analysis_peak-valley-detail',
        meta: {
          title: 'analysis_peak-valley-detail',
          i18nKey: 'route.analysis_peak-valley-detail'
        }
      },
      {
        name: 'analysis_peak-valley-scheme',
        path: '/analysis/peak-valley-scheme',
        component: 'view.analysis_peak-valley-scheme',
        meta: {
          title: 'analysis_peak-valley-scheme',
          i18nKey: 'route.analysis_peak-valley-scheme'
        }
      },
      {
        name: 'analysis_process-energy',
        path: '/analysis/process-energy',
        meta: {
          title: 'analysis_process-energy',
          i18nKey: 'route.analysis_process-energy'
        },
        children: [
          {
            name: 'analysis_process-energy_statistics',
            path: '/analysis/process-energy/statistics',
            meta: {
              title: 'analysis_process-energy_statistics',
              i18nKey: 'route.analysis_process-energy_statistics'
            },
            children: [
              {
                name: 'analysis_process-energy_statistics_daily',
                path: '/analysis/process-energy/statistics/daily',
                component: 'view.analysis_process-energy_statistics_daily',
                meta: {
                  title: 'analysis_process-energy_statistics_daily',
                  i18nKey: 'route.analysis_process-energy_statistics_daily'
                }
              },
              {
                name: 'analysis_process-energy_statistics_monthly',
                path: '/analysis/process-energy/statistics/monthly',
                component: 'view.analysis_process-energy_statistics_monthly',
                meta: {
                  title: 'analysis_process-energy_statistics_monthly',
                  i18nKey: 'route.analysis_process-energy_statistics_monthly'
                }
              },
              {
                name: 'analysis_process-energy_statistics_year',
                path: '/analysis/process-energy/statistics/year',
                component: 'view.analysis_process-energy_statistics_year',
                meta: {
                  title: 'analysis_process-energy_statistics_year',
                  i18nKey: 'route.analysis_process-energy_statistics_year'
                }
              }
            ]
          }
        ]
      },
      {
        name: 'analysis_product-output',
        path: '/analysis/product-output',
        component: 'view.analysis_product-output',
        meta: {
          title: 'analysis_product-output',
          i18nKey: 'route.analysis_product-output'
        }
      },
      {
        name: 'analysis_statistical',
        path: '/analysis/statistical',
        meta: {
          title: 'analysis_statistical',
          i18nKey: 'route.analysis_statistical'
        },
        children: [
          {
            name: 'analysis_statistical_cost',
            path: '/analysis/statistical/cost',
            component: 'view.analysis_statistical_cost',
            meta: {
              title: 'analysis_statistical_cost',
              i18nKey: 'route.analysis_statistical_cost'
            }
          },
          {
            name: 'analysis_statistical_flow',
            path: '/analysis/statistical/flow',
            component: 'view.analysis_statistical_flow',
            meta: {
              title: 'analysis_statistical_flow',
              i18nKey: 'route.analysis_statistical_flow'
            }
          },
          {
            name: 'analysis_statistical_yoy-mom',
            path: '/analysis/statistical/yoy-mom',
            component: 'view.analysis_statistical_yoy-mom',
            meta: {
              title: 'analysis_statistical_yoy-mom',
              i18nKey: 'route.analysis_statistical_yoy-mom'
            }
          }
        ]
      }
    ]
  },
  {
    name: 'approval',
    path: '/approval',
    component: 'layout.base',
    meta: {
      title: 'approval',
      i18nKey: 'route.approval'
    },
    children: [
      {
        name: 'approval_flow-designer',
        path: '/approval/flow-designer',
        component: 'view.approval_flow-designer',
        meta: {
          title: 'approval_flow-designer',
          i18nKey: 'route.approval_flow-designer'
        }
      },
      {
        name: 'approval_workspace',
        path: '/approval/workspace',
        component: 'view.approval_workspace',
        meta: {
          title: 'approval_workspace',
          i18nKey: 'route.approval_workspace'
        }
      }
    ]
  },
  {
    name: 'base-data',
    path: '/base-data',
    component: 'layout.base',
    meta: {
      title: 'base-data',
      i18nKey: 'route.base-data'
    },
    children: [
      {
        name: 'base-data_coefficient',
        path: '/base-data/coefficient',
        component: 'view.base-data_coefficient',
        meta: {
          title: 'base-data_coefficient',
          i18nKey: 'route.base-data_coefficient'
        }
      },
      {
        name: 'base-data_home',
        path: '/base-data/home',
        component: 'view.base-data_home',
        meta: {
          title: 'base-data_home',
          i18nKey: 'route.base-data_home'
        }
      },
      {
        name: 'base-data_medium',
        path: '/base-data/medium',
        component: 'view.base-data_medium',
        meta: {
          title: 'base-data_medium',
          i18nKey: 'route.base-data_medium'
        }
      },
      {
        name: 'base-data_meter',
        path: '/base-data/meter',
        component: 'view.base-data_meter',
        meta: {
          title: 'base-data_meter',
          i18nKey: 'route.base-data_meter'
        }
      },
      {
        name: 'base-data_power-distribution',
        path: '/base-data/power-distribution',
        component: 'view.base-data_power-distribution',
        meta: {
          title: 'base-data_power-distribution',
          i18nKey: 'route.base-data_power-distribution'
        }
      },
      {
        name: 'base-data_tou',
        path: '/base-data/tou',
        component: 'view.base-data_tou',
        meta: {
          title: 'base-data_tou',
          i18nKey: 'route.base-data_tou'
        }
      },
      {
        name: 'base-data_unit',
        path: '/base-data/unit',
        component: 'view.base-data_unit',
        meta: {
          title: 'base-data_unit',
          i18nKey: 'route.base-data_unit'
        }
      },
      {
        name: 'base-data_virtual-meter',
        path: '/base-data/virtual-meter',
        component: 'view.base-data_virtual-meter',
        meta: {
          title: 'base-data_virtual-meter',
          i18nKey: 'route.base-data_virtual-meter'
        }
      }
    ]
  },
  {
    name: 'cost',
    path: '/cost',
    component: 'layout.base',
    meta: {
      title: 'cost',
      i18nKey: 'route.cost'
    },
    children: [
      {
        name: 'cost_electricity',
        path: '/cost/electricity',
        component: 'view.cost_electricity',
        meta: {
          title: 'cost_electricity',
          i18nKey: 'route.cost_electricity'
        }
      },
      {
        name: 'cost_tactics',
        path: '/cost/tactics',
        component: 'view.cost_tactics',
        meta: {
          title: 'cost_tactics',
          i18nKey: 'route.cost_tactics'
        }
      },
      {
        name: 'cost_trend',
        path: '/cost/trend',
        component: 'view.cost_trend',
        meta: {
          title: 'cost_trend',
          i18nKey: 'route.cost_trend'
        }
      }
    ]
  },
  {
    name: 'dashboard',
    path: '/dashboard',
    component: 'layout.base',
    meta: {
      title: 'dashboard',
      i18nKey: 'route.dashboard'
    },
    children: [
      {
        name: 'dashboard_custom',
        path: '/dashboard/custom',
        component: 'view.dashboard_custom',
        meta: {
          title: 'dashboard_custom',
          i18nKey: 'route.dashboard_custom'
        }
      }
    ]
  },
  {
    name: 'developer',
    path: '/developer',
    component: 'layout.base',
    meta: {
      title: 'developer',
      i18nKey: 'route.developer'
    },
    children: [
      {
        name: 'developer_function',
        path: '/developer/function',
        meta: {
          title: 'developer_function',
          i18nKey: 'route.developer_function'
        },
        children: [
          {
            name: 'developer_function_hide-child',
            path: '/developer/function/hide-child',
            meta: {
              title: 'developer_function_hide-child',
              i18nKey: 'route.developer_function_hide-child'
            },
            children: [
              {
                name: 'developer_function_hide-child_one',
                path: '/developer/function/hide-child/one',
                component: 'view.developer_function_hide-child_one',
                meta: {
                  title: 'developer_function_hide-child_one',
                  i18nKey: 'route.developer_function_hide-child_one'
                }
              },
              {
                name: 'developer_function_hide-child_three',
                path: '/developer/function/hide-child/three',
                component: 'view.developer_function_hide-child_three',
                meta: {
                  title: 'developer_function_hide-child_three',
                  i18nKey: 'route.developer_function_hide-child_three'
                }
              },
              {
                name: 'developer_function_hide-child_two',
                path: '/developer/function/hide-child/two',
                component: 'view.developer_function_hide-child_two',
                meta: {
                  title: 'developer_function_hide-child_two',
                  i18nKey: 'route.developer_function_hide-child_two'
                }
              }
            ]
          },
          {
            name: 'developer_function_multi-tab',
            path: '/developer/function/multi-tab',
            component: 'view.developer_function_multi-tab',
            meta: {
              title: 'developer_function_multi-tab',
              i18nKey: 'route.developer_function_multi-tab'
            }
          },
          {
            name: 'developer_function_request',
            path: '/developer/function/request',
            component: 'view.developer_function_request',
            meta: {
              title: 'developer_function_request',
              i18nKey: 'route.developer_function_request'
            }
          },
          {
            name: 'developer_function_super-page',
            path: '/developer/function/super-page',
            component: 'view.developer_function_super-page',
            meta: {
              title: 'developer_function_super-page',
              i18nKey: 'route.developer_function_super-page'
            }
          },
          {
            name: 'developer_function_tab',
            path: '/developer/function/tab',
            component: 'view.developer_function_tab',
            meta: {
              title: 'developer_function_tab',
              i18nKey: 'route.developer_function_tab'
            }
          },
          {
            name: 'developer_function_toggle-auth',
            path: '/developer/function/toggle-auth',
            component: 'view.developer_function_toggle-auth',
            meta: {
              title: 'developer_function_toggle-auth',
              i18nKey: 'route.developer_function_toggle-auth'
            }
          }
        ]
      },
      {
        name: 'developer_plugin',
        path: '/developer/plugin',
        meta: {
          title: 'developer_plugin',
          i18nKey: 'route.developer_plugin'
        },
        children: [
          {
            name: 'developer_plugin_barcode',
            path: '/developer/plugin/barcode',
            component: 'view.developer_plugin_barcode',
            meta: {
              title: 'developer_plugin_barcode',
              i18nKey: 'route.developer_plugin_barcode'
            }
          },
          {
            name: 'developer_plugin_charts',
            path: '/developer/plugin/charts',
            meta: {
              title: 'developer_plugin_charts',
              i18nKey: 'route.developer_plugin_charts'
            },
            children: [
              {
                name: 'developer_plugin_charts_antv',
                path: '/developer/plugin/charts/antv',
                component: 'view.developer_plugin_charts_antv',
                meta: {
                  title: 'developer_plugin_charts_antv',
                  i18nKey: 'route.developer_plugin_charts_antv'
                }
              },
              {
                name: 'developer_plugin_charts_echarts',
                path: '/developer/plugin/charts/echarts',
                component: 'view.developer_plugin_charts_echarts',
                meta: {
                  title: 'developer_plugin_charts_echarts',
                  i18nKey: 'route.developer_plugin_charts_echarts'
                }
              },
              {
                name: 'developer_plugin_charts_vchart',
                path: '/developer/plugin/charts/vchart',
                component: 'view.developer_plugin_charts_vchart',
                meta: {
                  title: 'developer_plugin_charts_vchart',
                  i18nKey: 'route.developer_plugin_charts_vchart'
                }
              }
            ]
          },
          {
            name: 'developer_plugin_copy',
            path: '/developer/plugin/copy',
            component: 'view.developer_plugin_copy',
            meta: {
              title: 'developer_plugin_copy',
              i18nKey: 'route.developer_plugin_copy'
            }
          },
          {
            name: 'developer_plugin_editor',
            path: '/developer/plugin/editor',
            meta: {
              title: 'developer_plugin_editor',
              i18nKey: 'route.developer_plugin_editor'
            },
            children: [
              {
                name: 'developer_plugin_editor_markdown',
                path: '/developer/plugin/editor/markdown',
                component: 'view.developer_plugin_editor_markdown',
                meta: {
                  title: 'developer_plugin_editor_markdown',
                  i18nKey: 'route.developer_plugin_editor_markdown'
                }
              },
              {
                name: 'developer_plugin_editor_quill',
                path: '/developer/plugin/editor/quill',
                component: 'view.developer_plugin_editor_quill',
                meta: {
                  title: 'developer_plugin_editor_quill',
                  i18nKey: 'route.developer_plugin_editor_quill'
                }
              }
            ]
          },
          {
            name: 'developer_plugin_excel',
            path: '/developer/plugin/excel',
            component: 'view.developer_plugin_excel',
            meta: {
              title: 'developer_plugin_excel',
              i18nKey: 'route.developer_plugin_excel'
            }
          },
          {
            name: 'developer_plugin_gantt',
            path: '/developer/plugin/gantt',
            meta: {
              title: 'developer_plugin_gantt',
              i18nKey: 'route.developer_plugin_gantt'
            },
            children: [
              {
                name: 'developer_plugin_gantt_dhtmlx',
                path: '/developer/plugin/gantt/dhtmlx',
                component: 'view.developer_plugin_gantt_dhtmlx',
                meta: {
                  title: 'developer_plugin_gantt_dhtmlx',
                  i18nKey: 'route.developer_plugin_gantt_dhtmlx'
                }
              },
              {
                name: 'developer_plugin_gantt_vtable',
                path: '/developer/plugin/gantt/vtable',
                component: 'view.developer_plugin_gantt_vtable',
                meta: {
                  title: 'developer_plugin_gantt_vtable',
                  i18nKey: 'route.developer_plugin_gantt_vtable'
                }
              }
            ]
          },
          {
            name: 'developer_plugin_icon',
            path: '/developer/plugin/icon',
            component: 'view.developer_plugin_icon',
            meta: {
              title: 'developer_plugin_icon',
              i18nKey: 'route.developer_plugin_icon'
            }
          },
          {
            name: 'developer_plugin_map',
            path: '/developer/plugin/map',
            component: 'view.developer_plugin_map',
            meta: {
              title: 'developer_plugin_map',
              i18nKey: 'route.developer_plugin_map'
            }
          },
          {
            name: 'developer_plugin_pdf',
            path: '/developer/plugin/pdf',
            component: 'view.developer_plugin_pdf',
            meta: {
              title: 'developer_plugin_pdf',
              i18nKey: 'route.developer_plugin_pdf'
            }
          },
          {
            name: 'developer_plugin_pinyin',
            path: '/developer/plugin/pinyin',
            component: 'view.developer_plugin_pinyin',
            meta: {
              title: 'developer_plugin_pinyin',
              i18nKey: 'route.developer_plugin_pinyin'
            }
          },
          {
            name: 'developer_plugin_print',
            path: '/developer/plugin/print',
            component: 'view.developer_plugin_print',
            meta: {
              title: 'developer_plugin_print',
              i18nKey: 'route.developer_plugin_print'
            }
          },
          {
            name: 'developer_plugin_swiper',
            path: '/developer/plugin/swiper',
            component: 'view.developer_plugin_swiper',
            meta: {
              title: 'developer_plugin_swiper',
              i18nKey: 'route.developer_plugin_swiper'
            }
          },
          {
            name: 'developer_plugin_tables',
            path: '/developer/plugin/tables',
            meta: {
              title: 'developer_plugin_tables',
              i18nKey: 'route.developer_plugin_tables'
            },
            children: [
              {
                name: 'developer_plugin_tables_vtable',
                path: '/developer/plugin/tables/vtable',
                component: 'view.developer_plugin_tables_vtable',
                meta: {
                  title: 'developer_plugin_tables_vtable',
                  i18nKey: 'route.developer_plugin_tables_vtable'
                }
              }
            ]
          },
          {
            name: 'developer_plugin_typeit',
            path: '/developer/plugin/typeit',
            component: 'view.developer_plugin_typeit',
            meta: {
              title: 'developer_plugin_typeit',
              i18nKey: 'route.developer_plugin_typeit'
            }
          },
          {
            name: 'developer_plugin_video',
            path: '/developer/plugin/video',
            component: 'view.developer_plugin_video',
            meta: {
              title: 'developer_plugin_video',
              i18nKey: 'route.developer_plugin_video'
            }
          }
        ]
      }
    ]
  },
  {
    name: 'energy',
    path: '/energy',
    component: 'layout.base',
    meta: {
      title: 'energy',
      i18nKey: 'route.energy'
    },
    children: [
      {
        name: 'energy_branch-analysis',
        path: '/energy/branch-analysis',
        component: 'view.energy_branch-analysis',
        meta: {
          title: 'energy_branch-analysis',
          i18nKey: 'route.energy_branch-analysis'
        }
      },
      {
        name: 'energy_comparison',
        path: '/energy/comparison',
        component: 'view.energy_comparison',
        meta: {
          title: 'energy_comparison',
          i18nKey: 'route.energy_comparison',
          icon: 'carbon:compare'
        }
      },
      {
        name: 'energy_dashboard',
        path: '/energy/dashboard',
        component: 'view.energy_dashboard',
        meta: {
          title: 'energy_dashboard',
          i18nKey: 'route.energy_dashboard'
        }
      },
      {
        name: 'energy_electric-analysis',
        path: '/energy/electric-analysis',
        component: 'view.energy_electric-analysis',
        meta: {
          title: 'energy_electric-analysis',
          i18nKey: 'route.energy_electric-analysis'
        }
      },
      {
        name: 'energy_flow',
        path: '/energy/flow',
        component: 'view.energy_flow',
        meta: {
          title: 'energy_flow',
          i18nKey: 'route.energy_flow',
          icon: 'mdi:chart-sankey'
        }
      },
      {
        name: 'energy_history-data',
        path: '/energy/history-data',
        component: 'view.energy_history-data',
        meta: {
          title: 'energy_history-data',
          i18nKey: 'route.energy_history-data'
        }
      },
      {
        name: 'energy_ranking',
        path: '/energy/ranking',
        component: 'view.energy_ranking',
        meta: {
          title: 'energy_ranking',
          i18nKey: 'route.energy_ranking',
          icon: 'carbon:chart-radar'
        }
      },
      {
        name: 'energy_report',
        path: '/energy/report',
        component: 'view.energy_report',
        meta: {
          title: 'energy_report',
          i18nKey: 'route.energy_report'
        }
      }
    ]
  },
  {
    name: 'gatewaysetting',
    path: '/gatewaysetting',
    component: 'layout.base$view.gatewaysetting',
    meta: {
      title: 'gatewaysetting',
      i18nKey: 'route.gatewaysetting'
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'knowledge',
    path: '/knowledge',
    component: 'layout.base$view.knowledge',
    meta: {
      title: 'knowledge',
      i18nKey: 'route.knowledge'
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      icon: 'carbon:cloud-service-management',
      order: 9,
      roles: ['R_ADMIN']
    },
    children: [
      {
        name: 'manage_advanced-permission',
        path: '/manage/advanced-permission',
        component: 'view.manage_advanced-permission',
        meta: {
          title: 'manage_advanced-permission',
          i18nKey: 'route.manage_advanced-permission',
          icon: 'mdi:shield-lock',
          roles: ['R_ADMIN']
        }
      },
      {
        name: 'manage_api',
        path: '/manage/api',
        component: 'view.manage_api',
        meta: {
          title: 'manage_api',
          i18nKey: 'route.manage_api'
        }
      },
      {
        name: 'manage_department',
        path: '/manage/department',
        component: 'view.manage_department',
        meta: {
          title: 'manage_department',
          i18nKey: 'route.manage_department'
        }
      },
      {
        name: 'manage_dictionary',
        path: '/manage/dictionary',
        component: 'view.manage_dictionary',
        meta: {
          title: 'manage_dictionary',
          i18nKey: 'route.manage_dictionary'
        }
      },
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu',
          icon: 'material-symbols:route',
          order: 3,
          roles: ['R_ADMIN'],
          keepAlive: true
        }
      },
      {
        name: 'manage_operation-record',
        path: '/manage/operation-record',
        component: 'view.manage_operation-record',
        meta: {
          title: 'manage_operation-record',
          i18nKey: 'route.manage_operation-record'
        }
      },
      {
        name: 'manage_organization',
        path: '/manage/organization',
        component: 'view.manage_organization',
        meta: {
          title: 'manage_organization',
          i18nKey: 'route.manage_organization'
        }
      },
      {
        name: 'manage_password-change',
        path: '/manage/password-change',
        component: 'view.manage_password-change',
        meta: {
          title: 'manage_password-change',
          i18nKey: 'route.manage_password-change'
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role',
          icon: 'carbon:user-role',
          order: 2,
          roles: ['R_SUPER']
        }
      },
      {
        name: 'manage_route-menu-obsolete',
        path: '/manage/route-menu-obsolete',
        component: 'view.manage_route-menu-obsolete',
        meta: {
          title: 'manage_route-menu-obsolete',
          i18nKey: 'route.manage_route-menu-obsolete'
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user',
          icon: 'ic:round-manage-accounts',
          order: 1,
          roles: ['R_ADMIN']
        }
      },
      {
        name: 'manage_user-detail',
        path: '/manage/user-detail/:id',
        component: 'view.manage_user-detail',
        props: true,
        meta: {
          title: 'manage_user-detail',
          i18nKey: 'route.manage_user-detail',
          hideInMenu: true,
          roles: ['R_ADMIN'],
          activeMenu: 'manage_user'
        }
      },
      {
        name: 'manage_user-lock',
        path: '/manage/user-lock',
        component: 'view.manage_user-lock',
        meta: {
          title: 'manage_user-lock',
          i18nKey: 'route.manage_user-lock'
        }
      }
    ]
  },
  {
    name: 'profile',
    path: '/profile',
    component: 'layout.base',
    meta: {
      title: 'profile',
      i18nKey: 'route.profile'
    },
    children: [
      {
        name: 'profile_info',
        path: '/profile/info',
        component: 'view.profile_info',
        meta: {
          title: 'profile_info',
          i18nKey: 'route.profile_info'
        }
      },
      {
        name: 'profile_password',
        path: '/profile/password',
        component: 'view.profile_password',
        meta: {
          title: 'profile_password',
          i18nKey: 'route.profile_password'
        }
      }
    ]
  },
  {
    name: 'scheduling',
    path: '/scheduling',
    component: 'layout.base',
    meta: {
      title: 'scheduling',
      i18nKey: 'route.scheduling'
    },
    children: [
      {
        name: 'scheduling_calendar',
        path: '/scheduling/calendar',
        component: 'view.scheduling_calendar',
        meta: {
          title: 'scheduling_calendar',
          i18nKey: 'route.scheduling_calendar'
        }
      },
      {
        name: 'scheduling_factory-calendar',
        path: '/scheduling/factory-calendar',
        component: 'view.scheduling_factory-calendar',
        meta: {
          title: 'scheduling_factory-calendar',
          i18nKey: 'route.scheduling_factory-calendar'
        }
      },
      {
        name: 'scheduling_rule-config',
        path: '/scheduling/rule-config',
        component: 'view.scheduling_rule-config',
        meta: {
          title: 'scheduling_rule-config',
          i18nKey: 'route.scheduling_rule-config'
        }
      },
      {
        name: 'scheduling_rule-template',
        path: '/scheduling/rule-template',
        component: 'view.scheduling_rule-template',
        meta: {
          title: 'scheduling_rule-template',
          i18nKey: 'route.scheduling_rule-template'
        }
      },
      {
        name: 'scheduling_rule-version',
        path: '/scheduling/rule-version',
        component: 'view.scheduling_rule-version',
        meta: {
          title: 'scheduling_rule-version',
          i18nKey: 'route.scheduling_rule-version'
        }
      },
      {
        name: 'scheduling_shift',
        path: '/scheduling/shift',
        component: 'view.scheduling_shift',
        meta: {
          title: 'scheduling_shift',
          i18nKey: 'route.scheduling_shift'
        }
      },
      {
        name: 'scheduling_shift-pattern',
        path: '/scheduling/shift-pattern',
        component: 'view.scheduling_shift-pattern',
        meta: {
          title: 'scheduling_shift-pattern',
          i18nKey: 'route.scheduling_shift-pattern'
        }
      },
      {
        name: 'scheduling_team',
        path: '/scheduling/team',
        component: 'view.scheduling_team',
        meta: {
          title: 'scheduling_team',
          i18nKey: 'route.scheduling_team'
        }
      }
    ]
  },
  {
    name: 'sustainability',
    path: '/sustainability',
    component: 'layout.base',
    meta: {
      title: 'sustainability',
      i18nKey: 'route.sustainability'
    },
    children: [
      {
        name: 'sustainability_carbon-calculate',
        path: '/sustainability/carbon-calculate',
        component: 'view.sustainability_carbon-calculate',
        meta: {
          title: 'sustainability_carbon-calculate',
          i18nKey: 'route.sustainability_carbon-calculate'
        }
      },
      {
        name: 'sustainability_policy',
        path: '/sustainability/policy',
        component: 'view.sustainability_policy',
        meta: {
          title: 'sustainability_policy',
          i18nKey: 'route.sustainability_policy'
        }
      },
      {
        name: 'sustainability_program',
        path: '/sustainability/program',
        component: 'view.sustainability_program',
        meta: {
          title: 'sustainability_program',
          i18nKey: 'route.sustainability_program'
        }
      }
    ]
  }
];
