/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteRecordRaw, RouteComponent } from 'vue-router';
import type { ElegantConstRoute } from '@elegant-router/vue';
import type { RouteMap, RouteKey, RoutePath } from '@elegant-router/types';

/**
 * transform elegant const routes to vue routes
 * @param routes elegant const routes
 * @param layouts layout components
 * @param views view components
 */
export function transformElegantRoutesToVueRoutes(
  routes: ElegantConstRoute[],
  layouts: Record<string, RouteComponent | (() => Promise<RouteComponent>)>,
  views: Record<string, RouteComponent | (() => Promise<RouteComponent>)>
) {
  return routes.flatMap(route => transformElegantRouteToVueRoute(route, layouts, views));
}

/**
 * transform elegant route to vue route
 * @param route elegant const route
 * @param layouts layout components
 * @param views view components
 */
function transformElegantRouteToVueRoute(
  route: ElegantConstRoute,
  layouts: Record<string, RouteComponent | (() => Promise<RouteComponent>)>,
  views: Record<string, RouteComponent | (() => Promise<RouteComponent>)>
) {
  const LAYOUT_PREFIX = 'layout.';
  const VIEW_PREFIX = 'view.';
  const ROUTE_DEGREE_SPLITTER = '_';
  const FIRST_LEVEL_ROUTE_COMPONENT_SPLIT = '$';

  function isLayout(component: string) {
    return component.startsWith(LAYOUT_PREFIX);
  }

  function getLayoutName(component: string) {
    const layout = component.replace(LAYOUT_PREFIX, '');

    if(!layouts[layout]) {
      throw new Error(`Layout component "${layout}" not found`);
    }

    return layout;
  }

  function isView(component: string) {
    return component.startsWith(VIEW_PREFIX);
  }

  function getViewName(component: string) {
    const view = component.replace(VIEW_PREFIX, '');

    if(!views[view]) {
      throw new Error(`View component "${view}" not found`);
    }

    return view;
  }

  function isFirstLevelRoute(item: ElegantConstRoute) {
    return !item.name.includes(ROUTE_DEGREE_SPLITTER);
  }

  function isSingleLevelRoute(item: ElegantConstRoute) {
    return isFirstLevelRoute(item) && !item.children?.length;
  }

  function getSingleLevelRouteComponent(component: string) {
    const [layout, view] = component.split(FIRST_LEVEL_ROUTE_COMPONENT_SPLIT);

    return {
      layout: getLayoutName(layout),
      view: getViewName(view)
    };
  }

  const vueRoutes: RouteRecordRaw[] = [];

  // add props: true to route
  if (route.path.includes(':') && !route.props) {
    route.props = true;
  }

  const { name, path, component, children, ...rest } = route;

  const vueRoute = { name, path, ...rest } as RouteRecordRaw;

  try {
    if (component) {
      if (isSingleLevelRoute(route)) {
        const { layout, view } = getSingleLevelRouteComponent(component);

        const singleLevelRoute: RouteRecordRaw = {
          path,
          component: layouts[layout],
          meta: {
            title: route.meta?.title || ''
          },
          children: [
            {
              name,
              path: '',
              component: views[view],
              ...rest
            } as RouteRecordRaw
          ]
        };

        return [singleLevelRoute];
      }

      if (isLayout(component)) {
        const layoutName = getLayoutName(component);

        vueRoute.component = layouts[layoutName];
      }

      if (isView(component)) {
        const viewName = getViewName(component);

        vueRoute.component = views[viewName];
      }

    }
  } catch (error: any) {
    console.error(`Error transforming route "${route.name}": ${error.toString()}`);
    return [];
  }

  // add redirect to child
  if (children?.length && !vueRoute.redirect) {
    vueRoute.redirect = {
      name: children[0].name
    };
  }

  if (children?.length) {
    const childRoutes = children.flatMap(child => transformElegantRouteToVueRoute(child, layouts, views));

    if(isFirstLevelRoute(route)) {
      vueRoute.children = childRoutes;
    } else {
      vueRoutes.push(...childRoutes);
    }
  }

  vueRoutes.unshift(vueRoute);

  return vueRoutes;
}

/**
 * map of route name and route path
 */
const routeMap: RouteMap = {
  "root": "/",
  "not-found": "/:pathMatch(.*)*",
  "exception": "/exception",
  "exception_403": "/exception/403",
  "exception_404": "/exception/404",
  "exception_500": "/exception/500",
  "document": "/document",
  "document_project": "/document/project",
  "document_project-link": "/document/project-link",
  "document_vue": "/document/vue",
  "document_vite": "/document/vite",
  "document_unocss": "/document/unocss",
  "document_naive": "/document/naive",
  "document_antd": "/document/antd",
  "document_element-plus": "/document/element-plus",
  "403": "/403",
  "404": "/404",
  "500": "/500",
  "about": "/about",
  "alarm": "/alarm",
  "alarm_history": "/alarm/history",
  "alarm_item": "/alarm/item",
  "alarm_limit-type": "/alarm/limit-type",
  "analysis": "/analysis",
  "analysis_benchmark": "/analysis/benchmark",
  "analysis_branch": "/analysis/branch",
  "analysis_comprehensive": "/analysis/comprehensive",
  "analysis_consumption": "/analysis/consumption",
  "analysis_consumption-detail": "/analysis/consumption-detail",
  "analysis_energy": "/analysis/energy",
  "analysis_energy_comprehensive": "/analysis/energy/comprehensive",
  "analysis_energy_comprehensive_daily": "/analysis/energy/comprehensive/daily",
  "analysis_energy_comprehensive_monthly": "/analysis/energy/comprehensive/monthly",
  "analysis_energy_comprehensive_statistics": "/analysis/energy/comprehensive/statistics",
  "analysis_energy_comprehensive_year": "/analysis/energy/comprehensive/year",
  "analysis_indicators": "/analysis/indicators",
  "analysis_itemized": "/analysis/itemized",
  "analysis_itemized-detail": "/analysis/itemized-detail",
  "analysis_key-equipment": "/analysis/key-equipment",
  "analysis_key-equipment_daily": "/analysis/key-equipment/daily",
  "analysis_key-equipment_monthly": "/analysis/key-equipment/monthly",
  "analysis_key-equipment_year": "/analysis/key-equipment/year",
  "analysis_peak-valley": "/analysis/peak-valley",
  "analysis_peak-valley-detail": "/analysis/peak-valley-detail",
  "analysis_peak-valley-scheme": "/analysis/peak-valley-scheme",
  "analysis_process-energy": "/analysis/process-energy",
  "analysis_process-energy_statistics": "/analysis/process-energy/statistics",
  "analysis_process-energy_statistics_daily": "/analysis/process-energy/statistics/daily",
  "analysis_process-energy_statistics_monthly": "/analysis/process-energy/statistics/monthly",
  "analysis_process-energy_statistics_year": "/analysis/process-energy/statistics/year",
  "analysis_product-output": "/analysis/product-output",
  "analysis_statistical": "/analysis/statistical",
  "analysis_statistical_cost": "/analysis/statistical/cost",
  "analysis_statistical_flow": "/analysis/statistical/flow",
  "analysis_statistical_yoy-mom": "/analysis/statistical/yoy-mom",
  "approval": "/approval",
  "approval_flow-designer": "/approval/flow-designer",
  "approval_workspace": "/approval/workspace",
  "base-data": "/base-data",
  "base-data_coefficient": "/base-data/coefficient",
  "base-data_home": "/base-data/home",
  "base-data_medium": "/base-data/medium",
  "base-data_meter": "/base-data/meter",
  "base-data_power-distribution": "/base-data/power-distribution",
  "base-data_tou": "/base-data/tou",
  "base-data_unit": "/base-data/unit",
  "base-data_virtual-meter": "/base-data/virtual-meter",
  "cost": "/cost",
  "cost_electricity": "/cost/electricity",
  "cost_tactics": "/cost/tactics",
  "cost_trend": "/cost/trend",
  "dashboard": "/dashboard",
  "dashboard_custom": "/dashboard/custom",
  "developer": "/developer",
  "developer_function": "/developer/function",
  "developer_function_hide-child": "/developer/function/hide-child",
  "developer_function_hide-child_one": "/developer/function/hide-child/one",
  "developer_function_hide-child_three": "/developer/function/hide-child/three",
  "developer_function_hide-child_two": "/developer/function/hide-child/two",
  "developer_function_multi-tab": "/developer/function/multi-tab",
  "developer_function_request": "/developer/function/request",
  "developer_function_super-page": "/developer/function/super-page",
  "developer_function_tab": "/developer/function/tab",
  "developer_function_toggle-auth": "/developer/function/toggle-auth",
  "developer_plugin": "/developer/plugin",
  "developer_plugin_barcode": "/developer/plugin/barcode",
  "developer_plugin_charts": "/developer/plugin/charts",
  "developer_plugin_charts_antv": "/developer/plugin/charts/antv",
  "developer_plugin_charts_echarts": "/developer/plugin/charts/echarts",
  "developer_plugin_charts_vchart": "/developer/plugin/charts/vchart",
  "developer_plugin_copy": "/developer/plugin/copy",
  "developer_plugin_editor": "/developer/plugin/editor",
  "developer_plugin_editor_markdown": "/developer/plugin/editor/markdown",
  "developer_plugin_editor_quill": "/developer/plugin/editor/quill",
  "developer_plugin_excel": "/developer/plugin/excel",
  "developer_plugin_gantt": "/developer/plugin/gantt",
  "developer_plugin_gantt_dhtmlx": "/developer/plugin/gantt/dhtmlx",
  "developer_plugin_gantt_vtable": "/developer/plugin/gantt/vtable",
  "developer_plugin_icon": "/developer/plugin/icon",
  "developer_plugin_map": "/developer/plugin/map",
  "developer_plugin_pdf": "/developer/plugin/pdf",
  "developer_plugin_pinyin": "/developer/plugin/pinyin",
  "developer_plugin_print": "/developer/plugin/print",
  "developer_plugin_swiper": "/developer/plugin/swiper",
  "developer_plugin_tables": "/developer/plugin/tables",
  "developer_plugin_tables_vtable": "/developer/plugin/tables/vtable",
  "developer_plugin_typeit": "/developer/plugin/typeit",
  "developer_plugin_video": "/developer/plugin/video",
  "energy": "/energy",
  "energy_branch-analysis": "/energy/branch-analysis",
  "energy_comparison": "/energy/comparison",
  "energy_dashboard": "/energy/dashboard",
  "energy_electric-analysis": "/energy/electric-analysis",
  "energy_flow": "/energy/flow",
  "energy_history-data": "/energy/history-data",
  "energy_ranking": "/energy/ranking",
  "energy_report": "/energy/report",
  "gatewaysetting": "/gatewaysetting",
  "home": "/home",
  "iframe-page": "/iframe-page/:url",
  "knowledge": "/knowledge",
  "login": "/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?",
  "manage": "/manage",
  "manage_advanced-permission": "/manage/advanced-permission",
  "manage_api": "/manage/api",
  "manage_department": "/manage/department",
  "manage_dictionary": "/manage/dictionary",
  "manage_menu": "/manage/menu",
  "manage_operation-record": "/manage/operation-record",
  "manage_organization": "/manage/organization",
  "manage_password-change": "/manage/password-change",
  "manage_role": "/manage/role",
  "manage_route-menu-obsolete": "/manage/route-menu-obsolete",
  "manage_user": "/manage/user",
  "manage_user-detail": "/manage/user-detail/:id",
  "manage_user-lock": "/manage/user-lock",
  "profile": "/profile",
  "profile_info": "/profile/info",
  "profile_password": "/profile/password",
  "scheduling": "/scheduling",
  "scheduling_calendar": "/scheduling/calendar",
  "scheduling_factory-calendar": "/scheduling/factory-calendar",
  "scheduling_rule-config": "/scheduling/rule-config",
  "scheduling_rule-template": "/scheduling/rule-template",
  "scheduling_rule-version": "/scheduling/rule-version",
  "scheduling_shift": "/scheduling/shift",
  "scheduling_shift-pattern": "/scheduling/shift-pattern",
  "scheduling_team": "/scheduling/team",
  "sustainability": "/sustainability",
  "sustainability_carbon-calculate": "/sustainability/carbon-calculate",
  "sustainability_policy": "/sustainability/policy",
  "sustainability_program": "/sustainability/program"
};

/**
 * get route path by route name
 * @param name route name
 */
export function getRoutePath<T extends RouteKey>(name: T) {
  return routeMap[name];
}

/**
 * get route name by route path
 * @param path route path
 */
export function getRouteName(path: RoutePath) {
  const routeEntries = Object.entries(routeMap) as [RouteKey, RoutePath][];

  const routeName: RouteKey | null = routeEntries.find(([, routePath]) => routePath === path)?.[0] || null;

  return routeName;
}
