/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteRecordRaw, RouteComponent } from 'vue-router';
import type { ElegantConstRoute } from '@elegant-router/vue';
import type { RouteMap, RouteKey, RoutePath } from '@elegant-router/types';

/**
 * transform elegant const routes to vue routes
 * @param routes elegant const routes
 * @param layouts layout components
 * @param views view components
 */
export function transformElegantRoutesToVueRoutes(
  routes: ElegantConstRoute[],
  layouts: Record<string, RouteComponent | (() => Promise<RouteComponent>)>,
  views: Record<string, RouteComponent | (() => Promise<RouteComponent>)>
) {
  return routes.flatMap(route => transformElegantRouteToVueRoute(route, layouts, views));
}

/**
 * transform elegant route to vue route
 * @param route elegant const route
 * @param layouts layout components
 * @param views view components
 */
function transformElegantRouteToVueRoute(
  route: ElegantConstRoute,
  layouts: Record<string, RouteComponent | (() => Promise<RouteComponent>)>,
  views: Record<string, RouteComponent | (() => Promise<RouteComponent>)>
) {
  const LAYOUT_PREFIX = 'layout.';
  const VIEW_PREFIX = 'view.';
  const ROUTE_DEGREE_SPLITTER = '_';
  const FIRST_LEVEL_ROUTE_COMPONENT_SPLIT = '$';

  function isLayout(component: string) {
    return component.startsWith(LAYOUT_PREFIX);
  }

  function getLayoutName(component: string) {
    const layout = component.replace(LAYOUT_PREFIX, '');

    if(!layouts[layout]) {
      throw new Error(`Layout component "${layout}" not found`);
    }

    return layout;
  }

  function isView(component: string) {
    return component.startsWith(VIEW_PREFIX);
  }

  function getViewName(component: string) {
    const view = component.replace(VIEW_PREFIX, '');

    if(!views[view]) {
      throw new Error(`View component "${view}" not found`);
    }

    return view;
  }

  function isFirstLevelRoute(item: ElegantConstRoute) {
    return !item.name.includes(ROUTE_DEGREE_SPLITTER);
  }

  function isSingleLevelRoute(item: ElegantConstRoute) {
    return isFirstLevelRoute(item) && !item.children?.length;
  }

  function getSingleLevelRouteComponent(component: string) {
    const [layout, view] = component.split(FIRST_LEVEL_ROUTE_COMPONENT_SPLIT);

    return {
      layout: getLayoutName(layout),
      view: getViewName(view)
    };
  }

  const vueRoutes: RouteRecordRaw[] = [];

  // add props: true to route
  if (route.path.includes(':') && !route.props) {
    route.props = true;
  }

  const { name, path, component, children, ...rest } = route;

  const vueRoute = { name, path, ...rest } as RouteRecordRaw;

  try {
    if (component) {
      if (isSingleLevelRoute(route)) {
        const { layout, view } = getSingleLevelRouteComponent(component);

        const singleLevelRoute: RouteRecordRaw = {
          path,
          component: layouts[layout],
          meta: {
            title: route.meta?.title || ''
          },
          children: [
            {
              name,
              path: '',
              component: views[view],
              ...rest
            } as RouteRecordRaw
          ]
        };

        return [singleLevelRoute];
      }

      if (isLayout(component)) {
        const layoutName = getLayoutName(component);

        vueRoute.component = layouts[layoutName];
      }

      if (isView(component)) {
        const viewName = getViewName(component);

        vueRoute.component = views[viewName];
      }

    }
  } catch (error: any) {
    console.error(`Error transforming route "${route.name}": ${error.toString()}`);
    return [];
  }

  // add redirect to child
  if (children?.length && !vueRoute.redirect) {
    vueRoute.redirect = {
      name: children[0].name
    };
  }

  if (children?.length) {
    const childRoutes = children.flatMap(child => transformElegantRouteToVueRoute(child, layouts, views));

    if(isFirstLevelRoute(route)) {
      vueRoute.children = childRoutes;
    } else {
      vueRoutes.push(...childRoutes);
    }
  }

  vueRoutes.unshift(vueRoute);

  return vueRoutes;
}

/**
 * map of route name and route path
 */
const routeMap: RouteMap = {
  "root": "/",
  "not-found": "/:pathMatch(.*)*",
  "exception": "/exception",
  "exception_403": "/exception/403",
  "exception_404": "/exception/404",
  "exception_500": "/exception/500",
  "document": "/document",
  "document_project": "/document/project",
  "document_project-link": "/document/project-link",
  "document_vue": "/document/vue",
  "document_vite": "/document/vite",
  "document_unocss": "/document/unocss",
  "document_naive": "/document/naive",
  "document_antd": "/document/antd",
  "document_element-plus": "/document/element-plus",
  "document_alova": "/document/alova",
  "403": "/403",
  "404": "/404",
  "500": "/500",
  "about": "/about",
  "alarm": "/alarm",
  "alarm_history": "/alarm/history",
  "alarm_item": "/alarm/item",
  "alarm_limit-type": "/alarm/limit-type",
  "alova": "/alova",
  "alova_request": "/alova/request",
  "alova_scenes": "/alova/scenes",
  "alova_user": "/alova/user",
  "analysis": "/analysis",
  "analysis_consumption": "/analysis/consumption",
  "base-data": "/base-data",
  "base-data_coefficient": "/base-data/coefficient",
  "base-data_home": "/base-data/home",
  "base-data_medium": "/base-data/medium",
  "base-data_meter": "/base-data/meter",
  "base-data_power-distribution": "/base-data/power-distribution",
  "base-data_tou": "/base-data/tou",
  "base-data_unit": "/base-data/unit",
  "base-data_virtual-meter": "/base-data/virtual-meter",
  "benchmark": "/benchmark",
  "branchanalysis": "/branchanalysis",
  "carbonemission": "/carbonemission",
  "carbonemission_calculate": "/carbonemission/calculate",
  "comprehensivestatistics": "/comprehensivestatistics",
  "consumptionanalysis": "/consumptionanalysis",
  "cost": "/cost",
  "cost_electricity": "/cost/electricity",
  "cost_tactics": "/cost/tactics",
  "cost_trend": "/cost/trend",
  "costmanagement": "/costmanagement",
  "costmanagement_electricity": "/costmanagement/electricity",
  "costmanagement_tactics": "/costmanagement/tactics",
  "costmanagement_trend": "/costmanagement/trend",
  "energy": "/energy",
  "energy_base-data": "/energy/base-data",
  "energy_base-data_coefficient": "/energy/base-data/coefficient",
  "energy_base-data_ledger": "/energy/base-data/ledger",
  "energy_base-data_medium": "/energy/base-data/medium",
  "energy_base-data_meter": "/energy/base-data/meter",
  "energy_base-data_tou": "/energy/base-data/tou",
  "energy_base-data_unit": "/energy/base-data/unit",
  "energy_branch-analysis": "/energy/branch-analysis",
  "energy_comparison": "/energy/comparison",
  "energy_dashboard": "/energy/dashboard",
  "energy_electric-analysis": "/energy/electric-analysis",
  "energy_flow": "/energy/flow",
  "energy_ranking": "/energy/ranking",
  "energy_report": "/energy/report",
  "energy-analysis": "/energy-analysis",
  "energy-analysis_comprehensive": "/energy-analysis/comprehensive",
  "energy-analysis_comprehensive_daily": "/energy-analysis/comprehensive/daily",
  "energy-analysis_comprehensive_monthly": "/energy-analysis/comprehensive/monthly",
  "energy-analysis_comprehensive_statistics": "/energy-analysis/comprehensive/statistics",
  "energy-analysis_comprehensive_year": "/energy-analysis/comprehensive/year",
  "energy-indicators": "/energy-indicators",
  "function": "/function",
  "function_hide-child": "/function/hide-child",
  "function_hide-child_one": "/function/hide-child/one",
  "function_hide-child_three": "/function/hide-child/three",
  "function_hide-child_two": "/function/hide-child/two",
  "function_multi-tab": "/function/multi-tab",
  "function_request": "/function/request",
  "function_super-page": "/function/super-page",
  "function_tab": "/function/tab",
  "function_toggle-auth": "/function/toggle-auth",
  "gatewaysetting": "/gatewaysetting",
  "home": "/home",
  "iframe-page": "/iframe-page/:url",
  "itemized": "/itemized",
  "itemizedenergyanalysis": "/itemizedenergyanalysis",
  "keyequipment": "/keyequipment",
  "keyequipment_daily": "/keyequipment/daily",
  "keyequipment_monthly": "/keyequipment/monthly",
  "keyequipment_year": "/keyequipment/year",
  "knowledge": "/knowledge",
  "login": "/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?",
  "manage": "/manage",
  "manage_advanced-permission": "/manage/advanced-permission",
  "manage_api": "/manage/api",
  "manage_department": "/manage/department",
  "manage_dictionary": "/manage/dictionary",
  "manage_menu": "/manage/menu",
  "manage_operation-record": "/manage/operation-record",
  "manage_organization": "/manage/organization",
  "manage_role": "/manage/role",
  "manage_route-menu-obsolete": "/manage/route-menu-obsolete",
  "manage_user": "/manage/user",
  "manage_user-detail": "/manage/user-detail/:id",
  "peakvalley": "/peakvalley",
  "peakvalley-analysis": "/peakvalley-analysis",
  "plugin": "/plugin",
  "plugin_barcode": "/plugin/barcode",
  "plugin_charts": "/plugin/charts",
  "plugin_charts_antv": "/plugin/charts/antv",
  "plugin_charts_echarts": "/plugin/charts/echarts",
  "plugin_charts_vchart": "/plugin/charts/vchart",
  "plugin_copy": "/plugin/copy",
  "plugin_editor": "/plugin/editor",
  "plugin_editor_markdown": "/plugin/editor/markdown",
  "plugin_editor_quill": "/plugin/editor/quill",
  "plugin_excel": "/plugin/excel",
  "plugin_gantt": "/plugin/gantt",
  "plugin_gantt_dhtmlx": "/plugin/gantt/dhtmlx",
  "plugin_gantt_vtable": "/plugin/gantt/vtable",
  "plugin_icon": "/plugin/icon",
  "plugin_map": "/plugin/map",
  "plugin_pdf": "/plugin/pdf",
  "plugin_pinyin": "/plugin/pinyin",
  "plugin_print": "/plugin/print",
  "plugin_swiper": "/plugin/swiper",
  "plugin_tables": "/plugin/tables",
  "plugin_tables_vtable": "/plugin/tables/vtable",
  "plugin_typeit": "/plugin/typeit",
  "plugin_video": "/plugin/video",
  "process-energy": "/process-energy",
  "process-energy_statistics": "/process-energy/statistics",
  "process-energy_statistics_daily": "/process-energy/statistics/daily",
  "process-energy_statistics_monthly": "/process-energy/statistics/monthly",
  "process-energy_statistics_year": "/process-energy/statistics/year",
  "processenergy": "/processenergy",
  "productoutput": "/productoutput",
  "profile": "/profile",
  "profile_info": "/profile/info",
  "profile_password": "/profile/password",
  "saving": "/saving",
  "saving_policy": "/saving/policy",
  "saving_program": "/saving/program",
  "scheduling": "/scheduling",
  "scheduling_calendar": "/scheduling/calendar",
  "scheduling_factory-calendar": "/scheduling/factory-calendar",
  "scheduling_rule-config": "/scheduling/rule-config",
  "scheduling_rule-template": "/scheduling/rule-template",
  "scheduling_rule-version": "/scheduling/rule-version",
  "scheduling_shift": "/scheduling/shift",
  "scheduling_shift-pattern": "/scheduling/shift-pattern",
  "scheduling_team": "/scheduling/team",
  "spikesandvalleys": "/spikesandvalleys",
  "statistical": "/statistical",
  "statistical_cost": "/statistical/cost",
  "statistical_flow": "/statistical/flow",
  "statistical_yoy-mom": "/statistical/yoy-mom"
};

/**
 * get route path by route name
 * @param name route name
 */
export function getRoutePath<T extends RouteKey>(name: T) {
  return routeMap[name];
}

/**
 * get route name by route path
 * @param path route path
 */
export function getRouteName(path: RoutePath) {
  const routeEntries = Object.entries(routeMap) as [RouteKey, RoutePath][];

  const routeName: RouteKey | null = routeEntries.find(([, routePath]) => routePath === path)?.[0] || null;

  return routeName;
}
