/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

declare module "@elegant-router/types" {
  type ElegantConstRoute = import('@elegant-router/vue').ElegantConstRoute;

  /**
   * route layout
   */
  export type RouteLayout = "base" | "blank";

  /**
   * route map
   */
  export type RouteMap = {
    "root": "/";
    "not-found": "/:pathMatch(.*)*";
    "exception": "/exception";
    "exception_403": "/exception/403";
    "exception_404": "/exception/404";
    "exception_500": "/exception/500";
    "document": "/document";
    "document_project": "/document/project";
    "document_project-link": "/document/project-link";
    "document_vue": "/document/vue";
    "document_vite": "/document/vite";
    "document_unocss": "/document/unocss";
    "document_naive": "/document/naive";
    "document_antd": "/document/antd";
    "document_element-plus": "/document/element-plus";
    "403": "/403";
    "404": "/404";
    "500": "/500";
    "about": "/about";
    "alarm": "/alarm";
    "alarm_history": "/alarm/history";
    "alarm_item": "/alarm/item";
    "alarm_limit-type": "/alarm/limit-type";
    "analysis": "/analysis";
    "analysis_benchmark": "/analysis/benchmark";
    "analysis_branch": "/analysis/branch";
    "analysis_comprehensive": "/analysis/comprehensive";
    "analysis_consumption": "/analysis/consumption";
    "analysis_consumption-detail": "/analysis/consumption-detail";
    "analysis_energy": "/analysis/energy";
    "analysis_energy_comprehensive": "/analysis/energy/comprehensive";
    "analysis_energy_comprehensive_daily": "/analysis/energy/comprehensive/daily";
    "analysis_energy_comprehensive_monthly": "/analysis/energy/comprehensive/monthly";
    "analysis_energy_comprehensive_statistics": "/analysis/energy/comprehensive/statistics";
    "analysis_energy_comprehensive_year": "/analysis/energy/comprehensive/year";
    "analysis_indicators": "/analysis/indicators";
    "analysis_itemized": "/analysis/itemized";
    "analysis_itemized-detail": "/analysis/itemized-detail";
    "analysis_key-equipment": "/analysis/key-equipment";
    "analysis_key-equipment_daily": "/analysis/key-equipment/daily";
    "analysis_key-equipment_monthly": "/analysis/key-equipment/monthly";
    "analysis_key-equipment_year": "/analysis/key-equipment/year";
    "analysis_peak-valley": "/analysis/peak-valley";
    "analysis_peak-valley-detail": "/analysis/peak-valley-detail";
    "analysis_peak-valley-scheme": "/analysis/peak-valley-scheme";
    "analysis_process-energy": "/analysis/process-energy";
    "analysis_process-energy_statistics": "/analysis/process-energy/statistics";
    "analysis_process-energy_statistics_daily": "/analysis/process-energy/statistics/daily";
    "analysis_process-energy_statistics_monthly": "/analysis/process-energy/statistics/monthly";
    "analysis_process-energy_statistics_year": "/analysis/process-energy/statistics/year";
    "analysis_product-output": "/analysis/product-output";
    "analysis_statistical": "/analysis/statistical";
    "analysis_statistical_cost": "/analysis/statistical/cost";
    "analysis_statistical_flow": "/analysis/statistical/flow";
    "analysis_statistical_yoy-mom": "/analysis/statistical/yoy-mom";
    "approval": "/approval";
    "approval_flow-designer": "/approval/flow-designer";
    "approval_workspace": "/approval/workspace";
    "base-data": "/base-data";
    "base-data_coefficient": "/base-data/coefficient";
    "base-data_home": "/base-data/home";
    "base-data_medium": "/base-data/medium";
    "base-data_meter": "/base-data/meter";
    "base-data_power-distribution": "/base-data/power-distribution";
    "base-data_tou": "/base-data/tou";
    "base-data_unit": "/base-data/unit";
    "base-data_virtual-meter": "/base-data/virtual-meter";
    "cost": "/cost";
    "cost_electricity": "/cost/electricity";
    "cost_tactics": "/cost/tactics";
    "cost_trend": "/cost/trend";
    "dashboard": "/dashboard";
    "dashboard_custom": "/dashboard/custom";
    "developer": "/developer";
    "developer_function": "/developer/function";
    "developer_function_hide-child": "/developer/function/hide-child";
    "developer_function_hide-child_one": "/developer/function/hide-child/one";
    "developer_function_hide-child_three": "/developer/function/hide-child/three";
    "developer_function_hide-child_two": "/developer/function/hide-child/two";
    "developer_function_multi-tab": "/developer/function/multi-tab";
    "developer_function_request": "/developer/function/request";
    "developer_function_super-page": "/developer/function/super-page";
    "developer_function_tab": "/developer/function/tab";
    "developer_function_toggle-auth": "/developer/function/toggle-auth";
    "developer_plugin": "/developer/plugin";
    "developer_plugin_barcode": "/developer/plugin/barcode";
    "developer_plugin_charts": "/developer/plugin/charts";
    "developer_plugin_charts_antv": "/developer/plugin/charts/antv";
    "developer_plugin_charts_echarts": "/developer/plugin/charts/echarts";
    "developer_plugin_charts_vchart": "/developer/plugin/charts/vchart";
    "developer_plugin_copy": "/developer/plugin/copy";
    "developer_plugin_editor": "/developer/plugin/editor";
    "developer_plugin_editor_markdown": "/developer/plugin/editor/markdown";
    "developer_plugin_editor_quill": "/developer/plugin/editor/quill";
    "developer_plugin_excel": "/developer/plugin/excel";
    "developer_plugin_gantt": "/developer/plugin/gantt";
    "developer_plugin_gantt_dhtmlx": "/developer/plugin/gantt/dhtmlx";
    "developer_plugin_gantt_vtable": "/developer/plugin/gantt/vtable";
    "developer_plugin_icon": "/developer/plugin/icon";
    "developer_plugin_map": "/developer/plugin/map";
    "developer_plugin_pdf": "/developer/plugin/pdf";
    "developer_plugin_pinyin": "/developer/plugin/pinyin";
    "developer_plugin_print": "/developer/plugin/print";
    "developer_plugin_swiper": "/developer/plugin/swiper";
    "developer_plugin_tables": "/developer/plugin/tables";
    "developer_plugin_tables_vtable": "/developer/plugin/tables/vtable";
    "developer_plugin_typeit": "/developer/plugin/typeit";
    "developer_plugin_video": "/developer/plugin/video";
    "energy": "/energy";
    "energy_branch-analysis": "/energy/branch-analysis";
    "energy_comparison": "/energy/comparison";
    "energy_dashboard": "/energy/dashboard";
    "energy_electric-analysis": "/energy/electric-analysis";
    "energy_flow": "/energy/flow";
    "energy_history-data": "/energy/history-data";
    "energy_ranking": "/energy/ranking";
    "energy_report": "/energy/report";
    "gatewaysetting": "/gatewaysetting";
    "home": "/home";
    "iframe-page": "/iframe-page/:url";
    "knowledge": "/knowledge";
    "login": "/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?";
    "manage": "/manage";
    "manage_advanced-permission": "/manage/advanced-permission";
    "manage_api": "/manage/api";
    "manage_department": "/manage/department";
    "manage_dictionary": "/manage/dictionary";
    "manage_menu": "/manage/menu";
    "manage_operation-record": "/manage/operation-record";
    "manage_organization": "/manage/organization";
    "manage_password-change": "/manage/password-change";
    "manage_role": "/manage/role";
    "manage_route-menu-obsolete": "/manage/route-menu-obsolete";
    "manage_user": "/manage/user";
    "manage_user-detail": "/manage/user-detail/:id";
    "manage_user-lock": "/manage/user-lock";
    "profile": "/profile";
    "profile_info": "/profile/info";
    "profile_password": "/profile/password";
    "scheduling": "/scheduling";
    "scheduling_calendar": "/scheduling/calendar";
    "scheduling_factory-calendar": "/scheduling/factory-calendar";
    "scheduling_rule-config": "/scheduling/rule-config";
    "scheduling_rule-template": "/scheduling/rule-template";
    "scheduling_rule-version": "/scheduling/rule-version";
    "scheduling_shift": "/scheduling/shift";
    "scheduling_shift-pattern": "/scheduling/shift-pattern";
    "scheduling_team": "/scheduling/team";
    "sustainability": "/sustainability";
    "sustainability_carbon-calculate": "/sustainability/carbon-calculate";
    "sustainability_policy": "/sustainability/policy";
    "sustainability_program": "/sustainability/program";
  };

  /**
   * route key
   */
  export type RouteKey = keyof RouteMap;

  /**
   * route path
   */
  export type RoutePath = RouteMap[RouteKey];

  /**
   * custom route key
   */
  export type CustomRouteKey = Extract<
    RouteKey,
    | "root"
    | "not-found"
    | "exception"
    | "exception_403"
    | "exception_404"
    | "exception_500"
    | "document"
    | "document_project"
    | "document_project-link"
    | "document_vue"
    | "document_vite"
    | "document_unocss"
    | "document_naive"
    | "document_antd"
    | "document_element-plus"
  >;

  /**
   * the generated route key
   */
  export type GeneratedRouteKey = Exclude<RouteKey, CustomRouteKey>;

  /**
   * the first level route key, which contain the layout of the route
   */
  export type FirstLevelRouteKey = Extract<
    RouteKey,
    | "403"
    | "404"
    | "500"
    | "about"
    | "alarm"
    | "analysis"
    | "approval"
    | "base-data"
    | "cost"
    | "dashboard"
    | "developer"
    | "energy"
    | "gatewaysetting"
    | "home"
    | "iframe-page"
    | "knowledge"
    | "login"
    | "manage"
    | "profile"
    | "scheduling"
    | "sustainability"
  >;

  /**
   * the custom first level route key
   */
  export type CustomFirstLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
    | "exception"
    | "document"
  >;

  /**
   * the last level route key, which has the page file
   */
  export type LastLevelRouteKey = Extract<
    RouteKey,
    | "403"
    | "404"
    | "500"
    | "iframe-page"
    | "login"
    | "about"
    | "alarm_history"
    | "alarm_item"
    | "alarm_limit-type"
    | "analysis_benchmark"
    | "analysis_branch"
    | "analysis_comprehensive"
    | "analysis_consumption-detail"
    | "analysis_consumption"
    | "analysis_energy_comprehensive_daily"
    | "analysis_energy_comprehensive_monthly"
    | "analysis_energy_comprehensive_statistics"
    | "analysis_energy_comprehensive_year"
    | "analysis_indicators"
    | "analysis_itemized-detail"
    | "analysis_itemized"
    | "analysis_key-equipment_daily"
    | "analysis_key-equipment_monthly"
    | "analysis_key-equipment_year"
    | "analysis_peak-valley-detail"
    | "analysis_peak-valley-scheme"
    | "analysis_peak-valley"
    | "analysis_process-energy_statistics_daily"
    | "analysis_process-energy_statistics_monthly"
    | "analysis_process-energy_statistics_year"
    | "analysis_product-output"
    | "analysis_statistical_cost"
    | "analysis_statistical_flow"
    | "analysis_statistical_yoy-mom"
    | "approval_flow-designer"
    | "approval_workspace"
    | "base-data_coefficient"
    | "base-data_home"
    | "base-data_medium"
    | "base-data_meter"
    | "base-data_power-distribution"
    | "base-data_tou"
    | "base-data_unit"
    | "base-data_virtual-meter"
    | "cost_electricity"
    | "cost_tactics"
    | "cost_trend"
    | "dashboard_custom"
    | "developer_function_hide-child_one"
    | "developer_function_hide-child_three"
    | "developer_function_hide-child_two"
    | "developer_function_multi-tab"
    | "developer_function_request"
    | "developer_function_super-page"
    | "developer_function_tab"
    | "developer_function_toggle-auth"
    | "developer_plugin_barcode"
    | "developer_plugin_charts_antv"
    | "developer_plugin_charts_echarts"
    | "developer_plugin_charts_vchart"
    | "developer_plugin_copy"
    | "developer_plugin_editor_markdown"
    | "developer_plugin_editor_quill"
    | "developer_plugin_excel"
    | "developer_plugin_gantt_dhtmlx"
    | "developer_plugin_gantt_vtable"
    | "developer_plugin_icon"
    | "developer_plugin_map"
    | "developer_plugin_pdf"
    | "developer_plugin_pinyin"
    | "developer_plugin_print"
    | "developer_plugin_swiper"
    | "developer_plugin_tables_vtable"
    | "developer_plugin_typeit"
    | "developer_plugin_video"
    | "energy_branch-analysis"
    | "energy_comparison"
    | "energy_dashboard"
    | "energy_electric-analysis"
    | "energy_flow"
    | "energy_history-data"
    | "energy_ranking"
    | "energy_report"
    | "gatewaysetting"
    | "home"
    | "knowledge"
    | "manage_advanced-permission"
    | "manage_api"
    | "manage_department"
    | "manage_dictionary"
    | "manage_menu"
    | "manage_operation-record"
    | "manage_organization"
    | "manage_password-change"
    | "manage_role"
    | "manage_route-menu-obsolete"
    | "manage_user-detail"
    | "manage_user-lock"
    | "manage_user"
    | "profile_info"
    | "profile_password"
    | "scheduling_calendar"
    | "scheduling_factory-calendar"
    | "scheduling_rule-config"
    | "scheduling_rule-template"
    | "scheduling_rule-version"
    | "scheduling_shift-pattern"
    | "scheduling_shift"
    | "scheduling_team"
    | "sustainability_carbon-calculate"
    | "sustainability_policy"
    | "sustainability_program"
  >;

  /**
   * the custom last level route key
   */
  export type CustomLastLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
    | "exception_403"
    | "exception_404"
    | "exception_500"
    | "document_project"
    | "document_project-link"
    | "document_vue"
    | "document_vite"
    | "document_unocss"
    | "document_naive"
    | "document_antd"
    | "document_element-plus"
  >;

  /**
   * the single level route key
   */
  export type SingleLevelRouteKey = FirstLevelRouteKey & LastLevelRouteKey;

  /**
   * the custom single level route key
   */
  export type CustomSingleLevelRouteKey = CustomFirstLevelRouteKey & CustomLastLevelRouteKey;

  /**
   * the first level route key, but not the single level
  */
  export type FirstLevelRouteNotSingleKey = Exclude<FirstLevelRouteKey, SingleLevelRouteKey>;

  /**
   * the custom first level route key, but not the single level
   */
  export type CustomFirstLevelRouteNotSingleKey = Exclude<CustomFirstLevelRouteKey, CustomSingleLevelRouteKey>;

  /**
   * the center level route key
   */
  export type CenterLevelRouteKey = Exclude<GeneratedRouteKey, FirstLevelRouteKey | LastLevelRouteKey>;

  /**
   * the custom center level route key
   */
  export type CustomCenterLevelRouteKey = Exclude<CustomRouteKey, CustomFirstLevelRouteKey | CustomLastLevelRouteKey>;

  /**
   * the center level route key
   */
  type GetChildRouteKey<K extends RouteKey, T extends RouteKey = RouteKey> = T extends `${K}_${infer R}`
    ? R extends `${string}_${string}`
      ? never
      : T
    : never;

  /**
   * the single level route
   */
  type SingleLevelRoute<K extends SingleLevelRouteKey = SingleLevelRouteKey> = K extends string
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component: `layout.${RouteLayout}$view.${K}`;
      }
    : never;

  /**
   * the last level route
   */
  type LastLevelRoute<K extends GeneratedRouteKey> = K extends LastLevelRouteKey
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component: `view.${K}`;
      }
    : never;
  
  /**
   * the center level route
   */
  type CenterLevelRoute<K extends GeneratedRouteKey> = K extends CenterLevelRouteKey
    ? Omit<ElegantConstRoute, 'component'> & {
        name: K;
        path: RouteMap[K];
        children: (CenterLevelRoute<GetChildRouteKey<K>> | LastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the multi level route
   */
  type MultiLevelRoute<K extends FirstLevelRouteNotSingleKey = FirstLevelRouteNotSingleKey> = K extends string
    ? ElegantConstRoute & {
        name: K;
        path: RouteMap[K];
        component: `layout.${RouteLayout}`;
        children: (CenterLevelRoute<GetChildRouteKey<K>> | LastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;
  
  /**
   * the custom first level route
   */
  type CustomSingleLevelRoute<K extends CustomFirstLevelRouteKey = CustomFirstLevelRouteKey> = K extends string
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component?: `layout.${RouteLayout}$view.${LastLevelRouteKey}`;
      }
    : never;

  /**
   * the custom last level route
   */
  type CustomLastLevelRoute<K extends CustomRouteKey> = K extends CustomLastLevelRouteKey
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component?: `view.${LastLevelRouteKey}`;
      }
    : never;

  /**
   * the custom center level route
   */
  type CustomCenterLevelRoute<K extends CustomRouteKey> = K extends CustomCenterLevelRouteKey
    ? Omit<ElegantConstRoute, 'component'> & {
        name: K;
        path: RouteMap[K];
        children: (CustomCenterLevelRoute<GetChildRouteKey<K>> | CustomLastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the custom multi level route
   */
  type CustomMultiLevelRoute<K extends CustomFirstLevelRouteNotSingleKey = CustomFirstLevelRouteNotSingleKey> =
    K extends string
      ? ElegantConstRoute & {
          name: K;
          path: RouteMap[K];
          component: `layout.${RouteLayout}`;
          children: (CustomCenterLevelRoute<GetChildRouteKey<K>> | CustomLastLevelRoute<GetChildRouteKey<K>>)[];
        }
      : never;

  /**
   * the custom route
   */
  type CustomRoute = CustomSingleLevelRoute | CustomMultiLevelRoute;

  /**
   * the generated route
   */
  type GeneratedRoute = SingleLevelRoute | MultiLevelRoute;

  /**
   * the elegant route
   */
  type ElegantRoute = GeneratedRoute | CustomRoute;
}
