/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

declare module "@elegant-router/types" {
  type ElegantConstRoute = import('@elegant-router/vue').ElegantConstRoute;

  /**
   * route layout
   */
  export type RouteLayout = "base" | "blank";

  /**
   * route map
   */
  export type RouteMap = {
    "root": "/";
    "not-found": "/:pathMatch(.*)*";
    "exception": "/exception";
    "exception_403": "/exception/403";
    "exception_404": "/exception/404";
    "exception_500": "/exception/500";
    "document": "/document";
    "document_project": "/document/project";
    "document_project-link": "/document/project-link";
    "document_vue": "/document/vue";
    "document_vite": "/document/vite";
    "document_unocss": "/document/unocss";
    "document_naive": "/document/naive";
    "document_antd": "/document/antd";
    "document_element-plus": "/document/element-plus";
    "403": "/403";
    "404": "/404";
    "500": "/500";
    "about": "/about";
    "alarm": "/alarm";
    "alarm_history": "/alarm/history";
    "alarm_item": "/alarm/item";
    "alarm_limit-type": "/alarm/limit-type";
    "analysis": "/analysis";
    "analysis_consumption": "/analysis/consumption";
    "base-data": "/base-data";
    "base-data_coefficient": "/base-data/coefficient";
    "base-data_home": "/base-data/home";
    "base-data_medium": "/base-data/medium";
    "base-data_meter": "/base-data/meter";
    "base-data_power-distribution": "/base-data/power-distribution";
    "base-data_tou": "/base-data/tou";
    "base-data_unit": "/base-data/unit";
    "base-data_virtual-meter": "/base-data/virtual-meter";
    "benchmark": "/benchmark";
    "branchanalysis": "/branchanalysis";
    "carbonemission": "/carbonemission";
    "carbonemission_calculate": "/carbonemission/calculate";
    "comprehensivestatistics": "/comprehensivestatistics";
    "consumptionanalysis": "/consumptionanalysis";
    "cost": "/cost";
    "cost_electricity": "/cost/electricity";
    "cost_tactics": "/cost/tactics";
    "cost_trend": "/cost/trend";
    "costmanagement": "/costmanagement";
    "costmanagement_electricity": "/costmanagement/electricity";
    "costmanagement_tactics": "/costmanagement/tactics";
    "costmanagement_trend": "/costmanagement/trend";
    "energy": "/energy";
    "energy_base-data": "/energy/base-data";
    "energy_base-data_coefficient": "/energy/base-data/coefficient";
    "energy_base-data_ledger": "/energy/base-data/ledger";
    "energy_base-data_medium": "/energy/base-data/medium";
    "energy_base-data_meter": "/energy/base-data/meter";
    "energy_base-data_tou": "/energy/base-data/tou";
    "energy_base-data_unit": "/energy/base-data/unit";
    "energy_branch-analysis": "/energy/branch-analysis";
    "energy_comparison": "/energy/comparison";
    "energy_dashboard": "/energy/dashboard";
    "energy_electric-analysis": "/energy/electric-analysis";
    "energy_flow": "/energy/flow";
    "energy_history-data": "/energy/history-data";
    "energy_ranking": "/energy/ranking";
    "energy_report": "/energy/report";
    "energy-analysis": "/energy-analysis";
    "energy-analysis_comprehensive": "/energy-analysis/comprehensive";
    "energy-analysis_comprehensive_daily": "/energy-analysis/comprehensive/daily";
    "energy-analysis_comprehensive_monthly": "/energy-analysis/comprehensive/monthly";
    "energy-analysis_comprehensive_statistics": "/energy-analysis/comprehensive/statistics";
    "energy-analysis_comprehensive_year": "/energy-analysis/comprehensive/year";
    "energy-indicators": "/energy-indicators";
    "function": "/function";
    "function_hide-child": "/function/hide-child";
    "function_hide-child_one": "/function/hide-child/one";
    "function_hide-child_three": "/function/hide-child/three";
    "function_hide-child_two": "/function/hide-child/two";
    "function_multi-tab": "/function/multi-tab";
    "function_request": "/function/request";
    "function_super-page": "/function/super-page";
    "function_tab": "/function/tab";
    "function_toggle-auth": "/function/toggle-auth";
    "gatewaysetting": "/gatewaysetting";
    "home": "/home";
    "iframe-page": "/iframe-page/:url";
    "itemized": "/itemized";
    "itemizedenergyanalysis": "/itemizedenergyanalysis";
    "keyequipment": "/keyequipment";
    "keyequipment_daily": "/keyequipment/daily";
    "keyequipment_monthly": "/keyequipment/monthly";
    "keyequipment_year": "/keyequipment/year";
    "knowledge": "/knowledge";
    "login": "/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?";
    "manage": "/manage";
    "manage_advanced-permission": "/manage/advanced-permission";
    "manage_api": "/manage/api";
    "manage_department": "/manage/department";
    "manage_dictionary": "/manage/dictionary";
    "manage_menu": "/manage/menu";
    "manage_operation-record": "/manage/operation-record";
    "manage_organization": "/manage/organization";
    "manage_role": "/manage/role";
    "manage_route-menu-obsolete": "/manage/route-menu-obsolete";
    "manage_user": "/manage/user";
    "manage_user-detail": "/manage/user-detail/:id";
    "peakvalley": "/peakvalley";
    "peakvalley-analysis": "/peakvalley-analysis";
    "plugin": "/plugin";
    "plugin_barcode": "/plugin/barcode";
    "plugin_charts": "/plugin/charts";
    "plugin_charts_antv": "/plugin/charts/antv";
    "plugin_charts_echarts": "/plugin/charts/echarts";
    "plugin_charts_vchart": "/plugin/charts/vchart";
    "plugin_copy": "/plugin/copy";
    "plugin_editor": "/plugin/editor";
    "plugin_editor_markdown": "/plugin/editor/markdown";
    "plugin_editor_quill": "/plugin/editor/quill";
    "plugin_excel": "/plugin/excel";
    "plugin_gantt": "/plugin/gantt";
    "plugin_gantt_dhtmlx": "/plugin/gantt/dhtmlx";
    "plugin_gantt_vtable": "/plugin/gantt/vtable";
    "plugin_icon": "/plugin/icon";
    "plugin_map": "/plugin/map";
    "plugin_pdf": "/plugin/pdf";
    "plugin_pinyin": "/plugin/pinyin";
    "plugin_print": "/plugin/print";
    "plugin_swiper": "/plugin/swiper";
    "plugin_tables": "/plugin/tables";
    "plugin_tables_vtable": "/plugin/tables/vtable";
    "plugin_typeit": "/plugin/typeit";
    "plugin_video": "/plugin/video";
    "process-energy": "/process-energy";
    "process-energy_statistics": "/process-energy/statistics";
    "process-energy_statistics_daily": "/process-energy/statistics/daily";
    "process-energy_statistics_monthly": "/process-energy/statistics/monthly";
    "process-energy_statistics_year": "/process-energy/statistics/year";
    "processenergy": "/processenergy";
    "productoutput": "/productoutput";
    "profile": "/profile";
    "profile_info": "/profile/info";
    "profile_password": "/profile/password";
    "saving": "/saving";
    "saving_policy": "/saving/policy";
    "saving_program": "/saving/program";
    "scheduling": "/scheduling";
    "scheduling_calendar": "/scheduling/calendar";
    "scheduling_factory-calendar": "/scheduling/factory-calendar";
    "scheduling_rule-config": "/scheduling/rule-config";
    "scheduling_rule-template": "/scheduling/rule-template";
    "scheduling_rule-version": "/scheduling/rule-version";
    "scheduling_shift": "/scheduling/shift";
    "scheduling_shift-pattern": "/scheduling/shift-pattern";
    "scheduling_team": "/scheduling/team";
    "spikesandvalleys": "/spikesandvalleys";
    "statistical": "/statistical";
    "statistical_cost": "/statistical/cost";
    "statistical_flow": "/statistical/flow";
    "statistical_yoy-mom": "/statistical/yoy-mom";
  };

  /**
   * route key
   */
  export type RouteKey = keyof RouteMap;

  /**
   * route path
   */
  export type RoutePath = RouteMap[RouteKey];

  /**
   * custom route key
   */
  export type CustomRouteKey = Extract<
    RouteKey,
    | "root"
    | "not-found"
    | "exception"
    | "exception_403"
    | "exception_404"
    | "exception_500"
    | "document"
    | "document_project"
    | "document_project-link"
    | "document_vue"
    | "document_vite"
    | "document_unocss"
    | "document_naive"
    | "document_antd"
    | "document_element-plus"
  >;

  /**
   * the generated route key
   */
  export type GeneratedRouteKey = Exclude<RouteKey, CustomRouteKey>;

  /**
   * the first level route key, which contain the layout of the route
   */
  export type FirstLevelRouteKey = Extract<
    RouteKey,
    | "403"
    | "404"
    | "500"
    | "about"
    | "alarm"
    | "analysis"
    | "base-data"
    | "benchmark"
    | "branchanalysis"
    | "carbonemission"
    | "comprehensivestatistics"
    | "consumptionanalysis"
    | "cost"
    | "costmanagement"
    | "energy"
    | "energy-analysis"
    | "energy-indicators"
    | "function"
    | "gatewaysetting"
    | "home"
    | "iframe-page"
    | "itemized"
    | "itemizedenergyanalysis"
    | "keyequipment"
    | "knowledge"
    | "login"
    | "manage"
    | "peakvalley"
    | "peakvalley-analysis"
    | "plugin"
    | "process-energy"
    | "processenergy"
    | "productoutput"
    | "profile"
    | "saving"
    | "scheduling"
    | "spikesandvalleys"
    | "statistical"
  >;

  /**
   * the custom first level route key
   */
  export type CustomFirstLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
    | "exception"
    | "document"
  >;

  /**
   * the last level route key, which has the page file
   */
  export type LastLevelRouteKey = Extract<
    RouteKey,
    | "403"
    | "404"
    | "500"
    | "iframe-page"
    | "login"
    | "about"
    | "alarm_history"
    | "alarm_item"
    | "alarm_limit-type"
    | "analysis_consumption"
    | "base-data_coefficient"
    | "base-data_home"
    | "base-data_medium"
    | "base-data_meter"
    | "base-data_power-distribution"
    | "base-data_tou"
    | "base-data_unit"
    | "base-data_virtual-meter"
    | "benchmark"
    | "branchanalysis"
    | "carbonemission_calculate"
    | "comprehensivestatistics"
    | "consumptionanalysis"
    | "cost_electricity"
    | "cost_tactics"
    | "cost_trend"
    | "costmanagement_electricity"
    | "costmanagement_tactics"
    | "costmanagement_trend"
    | "energy-analysis_comprehensive_daily"
    | "energy-analysis_comprehensive_monthly"
    | "energy-analysis_comprehensive_statistics"
    | "energy-analysis_comprehensive_year"
    | "energy-indicators"
    | "energy_base-data_coefficient"
    | "energy_base-data_ledger"
    | "energy_base-data_medium"
    | "energy_base-data_meter"
    | "energy_base-data_tou"
    | "energy_base-data_unit"
    | "energy_branch-analysis"
    | "energy_comparison"
    | "energy_dashboard"
    | "energy_electric-analysis"
    | "energy_flow"
    | "energy_history-data"
    | "energy_ranking"
    | "energy_report"
    | "function_hide-child_one"
    | "function_hide-child_three"
    | "function_hide-child_two"
    | "function_multi-tab"
    | "function_request"
    | "function_super-page"
    | "function_tab"
    | "function_toggle-auth"
    | "gatewaysetting"
    | "home"
    | "itemized"
    | "itemizedenergyanalysis"
    | "keyequipment_daily"
    | "keyequipment_monthly"
    | "keyequipment_year"
    | "knowledge"
    | "manage_advanced-permission"
    | "manage_api"
    | "manage_department"
    | "manage_dictionary"
    | "manage_menu"
    | "manage_operation-record"
    | "manage_organization"
    | "manage_role"
    | "manage_route-menu-obsolete"
    | "manage_user-detail"
    | "manage_user"
    | "peakvalley-analysis"
    | "peakvalley"
    | "plugin_barcode"
    | "plugin_charts_antv"
    | "plugin_charts_echarts"
    | "plugin_charts_vchart"
    | "plugin_copy"
    | "plugin_editor_markdown"
    | "plugin_editor_quill"
    | "plugin_excel"
    | "plugin_gantt_dhtmlx"
    | "plugin_gantt_vtable"
    | "plugin_icon"
    | "plugin_map"
    | "plugin_pdf"
    | "plugin_pinyin"
    | "plugin_print"
    | "plugin_swiper"
    | "plugin_tables_vtable"
    | "plugin_typeit"
    | "plugin_video"
    | "process-energy_statistics_daily"
    | "process-energy_statistics_monthly"
    | "process-energy_statistics_year"
    | "processenergy"
    | "productoutput"
    | "profile_info"
    | "profile_password"
    | "saving_policy"
    | "saving_program"
    | "scheduling_calendar"
    | "scheduling_factory-calendar"
    | "scheduling_rule-config"
    | "scheduling_rule-template"
    | "scheduling_rule-version"
    | "scheduling_shift-pattern"
    | "scheduling_shift"
    | "scheduling_team"
    | "spikesandvalleys"
    | "statistical_cost"
    | "statistical_flow"
    | "statistical_yoy-mom"
  >;

  /**
   * the custom last level route key
   */
  export type CustomLastLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
    | "exception_403"
    | "exception_404"
    | "exception_500"
    | "document_project"
    | "document_project-link"
    | "document_vue"
    | "document_vite"
    | "document_unocss"
    | "document_naive"
    | "document_antd"
    | "document_element-plus"
  >;

  /**
   * the single level route key
   */
  export type SingleLevelRouteKey = FirstLevelRouteKey & LastLevelRouteKey;

  /**
   * the custom single level route key
   */
  export type CustomSingleLevelRouteKey = CustomFirstLevelRouteKey & CustomLastLevelRouteKey;

  /**
   * the first level route key, but not the single level
  */
  export type FirstLevelRouteNotSingleKey = Exclude<FirstLevelRouteKey, SingleLevelRouteKey>;

  /**
   * the custom first level route key, but not the single level
   */
  export type CustomFirstLevelRouteNotSingleKey = Exclude<CustomFirstLevelRouteKey, CustomSingleLevelRouteKey>;

  /**
   * the center level route key
   */
  export type CenterLevelRouteKey = Exclude<GeneratedRouteKey, FirstLevelRouteKey | LastLevelRouteKey>;

  /**
   * the custom center level route key
   */
  export type CustomCenterLevelRouteKey = Exclude<CustomRouteKey, CustomFirstLevelRouteKey | CustomLastLevelRouteKey>;

  /**
   * the center level route key
   */
  type GetChildRouteKey<K extends RouteKey, T extends RouteKey = RouteKey> = T extends `${K}_${infer R}`
    ? R extends `${string}_${string}`
      ? never
      : T
    : never;

  /**
   * the single level route
   */
  type SingleLevelRoute<K extends SingleLevelRouteKey = SingleLevelRouteKey> = K extends string
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component: `layout.${RouteLayout}$view.${K}`;
      }
    : never;

  /**
   * the last level route
   */
  type LastLevelRoute<K extends GeneratedRouteKey> = K extends LastLevelRouteKey
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component: `view.${K}`;
      }
    : never;
  
  /**
   * the center level route
   */
  type CenterLevelRoute<K extends GeneratedRouteKey> = K extends CenterLevelRouteKey
    ? Omit<ElegantConstRoute, 'component'> & {
        name: K;
        path: RouteMap[K];
        children: (CenterLevelRoute<GetChildRouteKey<K>> | LastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the multi level route
   */
  type MultiLevelRoute<K extends FirstLevelRouteNotSingleKey = FirstLevelRouteNotSingleKey> = K extends string
    ? ElegantConstRoute & {
        name: K;
        path: RouteMap[K];
        component: `layout.${RouteLayout}`;
        children: (CenterLevelRoute<GetChildRouteKey<K>> | LastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;
  
  /**
   * the custom first level route
   */
  type CustomSingleLevelRoute<K extends CustomFirstLevelRouteKey = CustomFirstLevelRouteKey> = K extends string
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component?: `layout.${RouteLayout}$view.${LastLevelRouteKey}`;
      }
    : never;

  /**
   * the custom last level route
   */
  type CustomLastLevelRoute<K extends CustomRouteKey> = K extends CustomLastLevelRouteKey
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component?: `view.${LastLevelRouteKey}`;
      }
    : never;

  /**
   * the custom center level route
   */
  type CustomCenterLevelRoute<K extends CustomRouteKey> = K extends CustomCenterLevelRouteKey
    ? Omit<ElegantConstRoute, 'component'> & {
        name: K;
        path: RouteMap[K];
        children: (CustomCenterLevelRoute<GetChildRouteKey<K>> | CustomLastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the custom multi level route
   */
  type CustomMultiLevelRoute<K extends CustomFirstLevelRouteNotSingleKey = CustomFirstLevelRouteNotSingleKey> =
    K extends string
      ? ElegantConstRoute & {
          name: K;
          path: RouteMap[K];
          component: `layout.${RouteLayout}`;
          children: (CustomCenterLevelRoute<GetChildRouteKey<K>> | CustomLastLevelRoute<GetChildRouteKey<K>>)[];
        }
      : never;

  /**
   * the custom route
   */
  type CustomRoute = CustomSingleLevelRoute | CustomMultiLevelRoute;

  /**
   * the generated route
   */
  type GeneratedRoute = SingleLevelRoute | MultiLevelRoute;

  /**
   * the elegant route
   */
  type ElegantRoute = GeneratedRoute | CustomRoute;
}
